// Mocks generated by Mockito 5.4.5 from annotations
// in app/test/src/presentation/notifiers/suite_user_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:app/src/domain/entities/v_user.dart' as _i3;
import 'package:app/src/domain/entities/v_user_detail.dart' as _i4;
import 'package:app/src/domain/models/suite_user.dart' as _i2;
import 'package:app/src/domain/models/v_post_list.dart' as _i5;
import 'package:app/src/domain/models/v_post_with_favorite_list.dart' as _i6;
import 'package:app/src/domain/usecases/fetch_user_post_favorite_usecase.dart' as _i12;
import 'package:app/src/domain/usecases/fetch_user_post_usecase.dart' as _i11;
import 'package:app/src/domain/usecases/find_user_detail_usecase.dart' as _i10;
import 'package:app/src/domain/usecases/find_user_usecase.dart' as _i9;
import 'package:app/src/domain/usecases/suite_user_usecase.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSuiteUser_0 extends _i1.SmartFake implements _i2.SuiteUser {
  _FakeSuiteUser_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeVUser_1 extends _i1.SmartFake implements _i3.VUser {
  _FakeVUser_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeVUserDetail_2 extends _i1.SmartFake implements _i4.VUserDetail {
  _FakeVUserDetail_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeVPostList_3 extends _i1.SmartFake implements _i5.VPostList {
  _FakeVPostList_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeVPostWithFavoriteList_4 extends _i1.SmartFake implements _i6.VPostWithFavoriteList {
  _FakeVPostWithFavoriteList_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [SuiteUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuiteUserUseCase extends _i1.Mock implements _i7.SuiteUserUseCase {
  @override
  _i8.Future<_i2.SuiteUser> execute() => (super.noSuchMethod(
        Invocation.method(#execute, []),
        returnValue: _i8.Future<_i2.SuiteUser>.value(
          _FakeSuiteUser_0(this, Invocation.method(#execute, [])),
        ),
        returnValueForMissingStub: _i8.Future<_i2.SuiteUser>.value(
          _FakeSuiteUser_0(this, Invocation.method(#execute, [])),
        ),
      ) as _i8.Future<_i2.SuiteUser>);
}

/// A class which mocks [FindUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFindUserUseCase extends _i1.Mock implements _i9.FindUserUseCase {
  @override
  _i8.Future<_i3.VUser> execute(String? userId) => (super.noSuchMethod(
        Invocation.method(#execute, [userId]),
        returnValue: _i8.Future<_i3.VUser>.value(
          _FakeVUser_1(this, Invocation.method(#execute, [userId])),
        ),
        returnValueForMissingStub: _i8.Future<_i3.VUser>.value(
          _FakeVUser_1(this, Invocation.method(#execute, [userId])),
        ),
      ) as _i8.Future<_i3.VUser>);
}

/// A class which mocks [FindUserDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFindUserDetailUseCase extends _i1.Mock implements _i10.FindUserDetailUseCase {
  @override
  _i8.Future<_i4.VUserDetail> execute(String? userId) => (super.noSuchMethod(
        Invocation.method(#execute, [userId]),
        returnValue: _i8.Future<_i4.VUserDetail>.value(
          _FakeVUserDetail_2(this, Invocation.method(#execute, [userId])),
        ),
        returnValueForMissingStub: _i8.Future<_i4.VUserDetail>.value(
          _FakeVUserDetail_2(this, Invocation.method(#execute, [userId])),
        ),
      ) as _i8.Future<_i4.VUserDetail>);
}

/// A class which mocks [FetchUserPostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchUserPostUseCase extends _i1.Mock implements _i11.FetchUserPostUseCase {
  @override
  _i8.Future<_i5.VPostList> execute({
    required String? userId,
    int? sincePostId,
    int? maxPostId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#execute, [], {
          #userId: userId,
          #sincePostId: sincePostId,
          #maxPostId: maxPostId,
        }),
        returnValue: _i8.Future<_i5.VPostList>.value(
          _FakeVPostList_3(
            this,
            Invocation.method(#execute, [], {
              #userId: userId,
              #sincePostId: sincePostId,
              #maxPostId: maxPostId,
            }),
          ),
        ),
        returnValueForMissingStub: _i8.Future<_i5.VPostList>.value(
          _FakeVPostList_3(
            this,
            Invocation.method(#execute, [], {
              #userId: userId,
              #sincePostId: sincePostId,
              #maxPostId: maxPostId,
            }),
          ),
        ),
      ) as _i8.Future<_i5.VPostList>);
}

/// A class which mocks [FetchUserPostFavoriteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchUserPostFavoriteUseCase extends _i1.Mock implements _i12.FetchUserPostFavoriteUseCase {
  @override
  _i8.Future<_i6.VPostWithFavoriteList> execute({
    required String? userId,
    DateTime? latestAt,
    DateTime? oldestAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#execute, [], {
          #userId: userId,
          #latestAt: latestAt,
          #oldestAt: oldestAt,
        }),
        returnValue: _i8.Future<_i6.VPostWithFavoriteList>.value(
          _FakeVPostWithFavoriteList_4(
            this,
            Invocation.method(#execute, [], {
              #userId: userId,
              #latestAt: latestAt,
              #oldestAt: oldestAt,
            }),
          ),
        ),
        returnValueForMissingStub: _i8.Future<_i6.VPostWithFavoriteList>.value(
          _FakeVPostWithFavoriteList_4(
            this,
            Invocation.method(#execute, [], {
              #userId: userId,
              #latestAt: latestAt,
              #oldestAt: oldestAt,
            }),
          ),
        ),
      ) as _i8.Future<_i6.VPostWithFavoriteList>);
}
