// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/presentation/pages/home/components/create_post_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i11;

import 'package:flutter/material.dart' as _i6;
import 'package:gynx_app/src/domain/models/suite_user.dart' as _i3;
import 'package:gynx_app/src/domain/usecases/suite_user_usecase.dart' as _i15;
import 'package:gynx_app/src/presentation/dialogs/loading_dialog.dart' as _i4;
import 'package:gynx_app/src/presentation/navigation/page_navigator.dart'
    as _i5;
import 'package:gynx_app/src/presentation/navigation/page_type.dart' as _i7;
import 'package:gynx_app/src/presentation/notifiers/timeline_notifier.dart'
    as _i14;
import 'package:gynx_app/src/presentation/pages/home/home_controller.dart'
    as _i13;
import 'package:image_picker/image_picker.dart' as _i12;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLostDataResponse_1 extends _i1.SmartFake
    implements _i2.LostDataResponse {
  _FakeLostDataResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSuiteUser_2 extends _i1.SmartFake implements _i3.SuiteUser {
  _FakeSuiteUser_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoadingDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadingDialog extends _i1.Mock implements _i4.LoadingDialog {
  @override
  void show() => super.noSuchMethod(
        Invocation.method(
          #show,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hide() => super.noSuchMethod(
        Invocation.method(
          #hide,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PageNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockPageNavigator extends _i1.Mock implements _i5.PageNavigator {
  @override
  void pop<T extends Object?>(
    _i6.BuildContext? context, [
    T? result,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #pop,
          [
            context,
            result,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void push(
    _i6.BuildContext? context,
    _i7.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #push,
          [
            context,
            pageType,
          ],
          {
            #pathParams: pathParams,
            #queryParams: queryParams,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void go(
    _i6.BuildContext? context,
    _i7.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #go,
          [
            context,
            pageType,
          ],
          {
            #pathParams: pathParams,
            #queryParams: queryParams,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushReplacement(
    _i6.BuildContext? context,
    _i7.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushReplacement,
          [
            context,
            pageType,
          ],
          {
            #pathParams: pathParams,
            #queryParams: queryParams,
          },
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [XFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockXFile extends _i1.Mock implements _i2.XFile {
  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  _i9.Future<void> saveTo(String? path) => (super.noSuchMethod(
        Invocation.method(
          #saveTo,
          [path],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<int> length() => (super.noSuchMethod(
        Invocation.method(
          #length,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
        returnValueForMissingStub: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<String> readAsString(
          {_i10.Encoding? encoding = const _i10.Utf8Codec()}) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAsString,
          [],
          {#encoding: encoding},
        ),
        returnValue: _i9.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #readAsString,
            [],
            {#encoding: encoding},
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #readAsString,
            [],
            {#encoding: encoding},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i11.Uint8List> readAsBytes() => (super.noSuchMethod(
        Invocation.method(
          #readAsBytes,
          [],
        ),
        returnValue: _i9.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
        returnValueForMissingStub:
            _i9.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
      ) as _i9.Future<_i11.Uint8List>);

  @override
  _i9.Stream<_i11.Uint8List> openRead([
    int? start,
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #openRead,
          [
            start,
            end,
          ],
        ),
        returnValue: _i9.Stream<_i11.Uint8List>.empty(),
        returnValueForMissingStub: _i9.Stream<_i11.Uint8List>.empty(),
      ) as _i9.Stream<_i11.Uint8List>);

  @override
  _i9.Future<DateTime> lastModified() => (super.noSuchMethod(
        Invocation.method(
          #lastModified,
          [],
        ),
        returnValue: _i9.Future<DateTime>.value(_FakeDateTime_0(
          this,
          Invocation.method(
            #lastModified,
            [],
          ),
        )),
        returnValueForMissingStub: _i9.Future<DateTime>.value(_FakeDateTime_0(
          this,
          Invocation.method(
            #lastModified,
            [],
          ),
        )),
      ) as _i9.Future<DateTime>);
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i12.ImagePicker {
  @override
  _i9.Future<_i2.XFile?> pickImage({
    required _i2.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i2.CameraDevice? preferredCameraDevice = _i2.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImage,
          [],
          {
            #source: source,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #preferredCameraDevice: preferredCameraDevice,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i9.Future<_i2.XFile?>.value(),
        returnValueForMissingStub: _i9.Future<_i2.XFile?>.value(),
      ) as _i9.Future<_i2.XFile?>);

  @override
  _i9.Future<List<_i2.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultiImage,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i9.Future<List<_i2.XFile>>.value(<_i2.XFile>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i2.XFile>>.value(<_i2.XFile>[]),
      ) as _i9.Future<List<_i2.XFile>>);

  @override
  _i9.Future<_i2.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i9.Future<_i2.XFile?>.value(),
        returnValueForMissingStub: _i9.Future<_i2.XFile?>.value(),
      ) as _i9.Future<_i2.XFile?>);

  @override
  _i9.Future<List<_i2.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickMultipleMedia,
          [],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #imageQuality: imageQuality,
            #limit: limit,
            #requestFullMetadata: requestFullMetadata,
          },
        ),
        returnValue: _i9.Future<List<_i2.XFile>>.value(<_i2.XFile>[]),
        returnValueForMissingStub:
            _i9.Future<List<_i2.XFile>>.value(<_i2.XFile>[]),
      ) as _i9.Future<List<_i2.XFile>>);

  @override
  _i9.Future<_i2.XFile?> pickVideo({
    required _i2.ImageSource? source,
    _i2.CameraDevice? preferredCameraDevice = _i2.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickVideo,
          [],
          {
            #source: source,
            #preferredCameraDevice: preferredCameraDevice,
            #maxDuration: maxDuration,
          },
        ),
        returnValue: _i9.Future<_i2.XFile?>.value(),
        returnValueForMissingStub: _i9.Future<_i2.XFile?>.value(),
      ) as _i9.Future<_i2.XFile?>);

  @override
  _i9.Future<_i2.LostDataResponse> retrieveLostData() => (super.noSuchMethod(
        Invocation.method(
          #retrieveLostData,
          [],
        ),
        returnValue:
            _i9.Future<_i2.LostDataResponse>.value(_FakeLostDataResponse_1(
          this,
          Invocation.method(
            #retrieveLostData,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i2.LostDataResponse>.value(_FakeLostDataResponse_1(
          this,
          Invocation.method(
            #retrieveLostData,
            [],
          ),
        )),
      ) as _i9.Future<_i2.LostDataResponse>);

  @override
  bool supportsImageSource(_i2.ImageSource? source) => (super.noSuchMethod(
        Invocation.method(
          #supportsImageSource,
          [source],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [HomeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeController extends _i1.Mock implements _i13.HomeController {
  @override
  _i9.Future<void> createPost({
    required _i14.TimelineNotifier? timelineNotifier,
    required String? text,
    required List<String>? mediaPaths,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [],
          {
            #timelineNotifier: timelineNotifier,
            #text: text,
            #mediaPaths: mediaPaths,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [SuiteUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuiteUserUseCase extends _i1.Mock implements _i15.SuiteUserUseCase {
  @override
  _i9.Future<_i3.SuiteUser> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i9.Future<_i3.SuiteUser>.value(_FakeSuiteUser_2(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i3.SuiteUser>.value(_FakeSuiteUser_2(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i9.Future<_i3.SuiteUser>);
}
