// Mocks generated by Mockito 5.4.5 from annotations
// in app/test/src/application/interactors/check_gynx_id_existence_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/src/domain/entities/t_user.dart' as _i2;
import 'package:app/src/domain/repositories/t_user_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTUser_0 extends _i1.SmartFake implements _i2.TUser {
  _FakeTUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTUserRepository extends _i1.Mock implements _i3.TUserRepository {
  @override
  _i4.Future<_i2.TUser> findByPrimaryKey(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#findByPrimaryKey, [id]),
            returnValue: _i4.Future<_i2.TUser>.value(
              _FakeTUser_0(this, Invocation.method(#findByPrimaryKey, [id])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.TUser>.value(
              _FakeTUser_0(this, Invocation.method(#findByPrimaryKey, [id])),
            ),
          )
          as _i4.Future<_i2.TUser>);

  @override
  _i4.Future<_i2.TUser> findByGynxId(String? gynxId) =>
      (super.noSuchMethod(
            Invocation.method(#findByGynxId, [gynxId]),
            returnValue: _i4.Future<_i2.TUser>.value(
              _FakeTUser_0(this, Invocation.method(#findByGynxId, [gynxId])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.TUser>.value(
              _FakeTUser_0(this, Invocation.method(#findByGynxId, [gynxId])),
            ),
          )
          as _i4.Future<_i2.TUser>);

  @override
  _i4.Future<bool> existsById(String? gynxId) =>
      (super.noSuchMethod(
            Invocation.method(#existsById, [gynxId]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateByPrimaryKey({
    required String? id,
    required String? gynxId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateByPrimaryKey, [], {
              #id: id,
              #gynxId: gynxId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
