// Mocks generated by Mockito 5.4.5 from annotations
// in app/test/src/application/interactors/update_user_profile_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i8;
import 'dart:io' as _i2;
import 'dart:typed_data' as _i9;

import 'package:app/src/domain/entities/t_user.dart' as _i4;
import 'package:app/src/domain/entities/t_user_profile.dart' as _i5;
import 'package:app/src/domain/entities/user.dart' as _i3;
import 'package:app/src/domain/enums/oauth_provider_type.dart' as _i10;
import 'package:app/src/domain/enums/storage_type.dart' as _i14;
import 'package:app/src/domain/generators/uuid_generator.dart' as _i11;
import 'package:app/src/domain/repositories/auth_repository.dart' as _i12;
import 'package:app/src/domain/repositories/storage_repository.dart' as _i13;
import 'package:app/src/domain/repositories/t_user_profile_repository.dart' as _i16;
import 'package:app/src/domain/repositories/t_user_repository.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFile_0 extends _i1.SmartFake implements _i2.File {
  _FakeFile_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeUri_1 extends _i1.SmartFake implements Uri {
  _FakeUri_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeDirectory_2 extends _i1.SmartFake implements _i2.Directory {
  _FakeDirectory_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_3 extends _i1.SmartFake implements _i2.FileSystemEntity {
  _FakeFileSystemEntity_3(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeDateTime_4 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_4(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_5 extends _i1.SmartFake implements _i2.RandomAccessFile {
  _FakeRandomAccessFile_5(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeIOSink_6 extends _i1.SmartFake implements _i2.IOSink {
  _FakeIOSink_6(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeFileStat_7 extends _i1.SmartFake implements _i2.FileStat {
  _FakeFileStat_7(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _Fake$UserCopyWith_8<$Res> extends _i1.SmartFake implements _i3.$UserCopyWith<$Res> {
  _Fake$UserCopyWith_8(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeTUser_9 extends _i1.SmartFake implements _i4.TUser {
  _FakeTUser_9(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeTUserProfile_10 extends _i1.SmartFake implements _i5.TUserProfile {
  _FakeTUserProfile_10(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i2.File {
  @override
  _i2.File get absolute => (super.noSuchMethod(
        Invocation.getter(#absolute),
        returnValue: _FakeFile_0(this, Invocation.getter(#absolute)),
        returnValueForMissingStub: _FakeFile_0(
          this,
          Invocation.getter(#absolute),
        ),
      ) as _i2.File);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i6.dummyValue<String>(this, Invocation.getter(#path)),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  Uri get uri => (super.noSuchMethod(
        Invocation.getter(#uri),
        returnValue: _FakeUri_1(this, Invocation.getter(#uri)),
        returnValueForMissingStub: _FakeUri_1(
          this,
          Invocation.getter(#uri),
        ),
      ) as Uri);

  @override
  bool get isAbsolute => (super.noSuchMethod(
        Invocation.getter(#isAbsolute),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Directory get parent => (super.noSuchMethod(
        Invocation.getter(#parent),
        returnValue: _FakeDirectory_2(this, Invocation.getter(#parent)),
        returnValueForMissingStub: _FakeDirectory_2(
          this,
          Invocation.getter(#parent),
        ),
      ) as _i2.Directory);

  @override
  _i7.Future<_i2.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#create, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValue: _i7.Future<_i2.File>.value(
          _FakeFile_0(
            this,
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
          ),
        ),
        returnValueForMissingStub: _i7.Future<_i2.File>.value(
          _FakeFile_0(
            this,
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
          ),
        ),
      ) as _i7.Future<_i2.File>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) => super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.File> rename(String? newPath) => (super.noSuchMethod(
        Invocation.method(#rename, [newPath]),
        returnValue: _i7.Future<_i2.File>.value(
          _FakeFile_0(this, Invocation.method(#rename, [newPath])),
        ),
        returnValueForMissingStub: _i7.Future<_i2.File>.value(
          _FakeFile_0(this, Invocation.method(#rename, [newPath])),
        ),
      ) as _i7.Future<_i2.File>);

  @override
  _i2.File renameSync(String? newPath) => (super.noSuchMethod(
        Invocation.method(#renameSync, [newPath]),
        returnValue: _FakeFile_0(
          this,
          Invocation.method(#renameSync, [newPath]),
        ),
        returnValueForMissingStub: _FakeFile_0(
          this,
          Invocation.method(#renameSync, [newPath]),
        ),
      ) as _i2.File);

  @override
  _i7.Future<_i2.FileSystemEntity> delete({bool? recursive = false}) => (super.noSuchMethod(
        Invocation.method(#delete, [], {#recursive: recursive}),
        returnValue: _i7.Future<_i2.FileSystemEntity>.value(
          _FakeFileSystemEntity_3(
            this,
            Invocation.method(#delete, [], {#recursive: recursive}),
          ),
        ),
        returnValueForMissingStub: _i7.Future<_i2.FileSystemEntity>.value(
          _FakeFileSystemEntity_3(
            this,
            Invocation.method(#delete, [], {#recursive: recursive}),
          ),
        ),
      ) as _i7.Future<_i2.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
        Invocation.method(#deleteSync, [], {#recursive: recursive}),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.File> copy(String? newPath) => (super.noSuchMethod(
        Invocation.method(#copy, [newPath]),
        returnValue: _i7.Future<_i2.File>.value(
          _FakeFile_0(this, Invocation.method(#copy, [newPath])),
        ),
        returnValueForMissingStub: _i7.Future<_i2.File>.value(
          _FakeFile_0(this, Invocation.method(#copy, [newPath])),
        ),
      ) as _i7.Future<_i2.File>);

  @override
  _i2.File copySync(String? newPath) => (super.noSuchMethod(
        Invocation.method(#copySync, [newPath]),
        returnValue: _FakeFile_0(
          this,
          Invocation.method(#copySync, [newPath]),
        ),
        returnValueForMissingStub: _FakeFile_0(
          this,
          Invocation.method(#copySync, [newPath]),
        ),
      ) as _i2.File);

  @override
  _i7.Future<int> length() => (super.noSuchMethod(
        Invocation.method(#length, []),
        returnValue: _i7.Future<int>.value(0),
        returnValueForMissingStub: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  int lengthSync() => (super.noSuchMethod(
        Invocation.method(#lengthSync, []),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i7.Future<DateTime> lastAccessed() => (super.noSuchMethod(
        Invocation.method(#lastAccessed, []),
        returnValue: _i7.Future<DateTime>.value(
          _FakeDateTime_4(this, Invocation.method(#lastAccessed, [])),
        ),
        returnValueForMissingStub: _i7.Future<DateTime>.value(
          _FakeDateTime_4(this, Invocation.method(#lastAccessed, [])),
        ),
      ) as _i7.Future<DateTime>);

  @override
  DateTime lastAccessedSync() => (super.noSuchMethod(
        Invocation.method(#lastAccessedSync, []),
        returnValue: _FakeDateTime_4(
          this,
          Invocation.method(#lastAccessedSync, []),
        ),
        returnValueForMissingStub: _FakeDateTime_4(
          this,
          Invocation.method(#lastAccessedSync, []),
        ),
      ) as DateTime);

  @override
  _i7.Future<dynamic> setLastAccessed(DateTime? time) => (super.noSuchMethod(
        Invocation.method(#setLastAccessed, [time]),
        returnValue: _i7.Future<dynamic>.value(),
        returnValueForMissingStub: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
        Invocation.method(#setLastAccessedSync, [time]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<DateTime> lastModified() => (super.noSuchMethod(
        Invocation.method(#lastModified, []),
        returnValue: _i7.Future<DateTime>.value(
          _FakeDateTime_4(this, Invocation.method(#lastModified, [])),
        ),
        returnValueForMissingStub: _i7.Future<DateTime>.value(
          _FakeDateTime_4(this, Invocation.method(#lastModified, [])),
        ),
      ) as _i7.Future<DateTime>);

  @override
  DateTime lastModifiedSync() => (super.noSuchMethod(
        Invocation.method(#lastModifiedSync, []),
        returnValue: _FakeDateTime_4(
          this,
          Invocation.method(#lastModifiedSync, []),
        ),
        returnValueForMissingStub: _FakeDateTime_4(
          this,
          Invocation.method(#lastModifiedSync, []),
        ),
      ) as DateTime);

  @override
  _i7.Future<dynamic> setLastModified(DateTime? time) => (super.noSuchMethod(
        Invocation.method(#setLastModified, [time]),
        returnValue: _i7.Future<dynamic>.value(),
        returnValueForMissingStub: _i7.Future<dynamic>.value(),
      ) as _i7.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
        Invocation.method(#setLastModifiedSync, [time]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.RandomAccessFile> open({
    _i2.FileMode? mode = _i2.FileMode.read,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#open, [], {#mode: mode}),
        returnValue: _i7.Future<_i2.RandomAccessFile>.value(
          _FakeRandomAccessFile_5(
            this,
            Invocation.method(#open, [], {#mode: mode}),
          ),
        ),
        returnValueForMissingStub: _i7.Future<_i2.RandomAccessFile>.value(
          _FakeRandomAccessFile_5(
            this,
            Invocation.method(#open, [], {#mode: mode}),
          ),
        ),
      ) as _i7.Future<_i2.RandomAccessFile>);

  @override
  _i2.RandomAccessFile openSync({_i2.FileMode? mode = _i2.FileMode.read}) => (super.noSuchMethod(
        Invocation.method(#openSync, [], {#mode: mode}),
        returnValue: _FakeRandomAccessFile_5(
          this,
          Invocation.method(#openSync, [], {#mode: mode}),
        ),
        returnValueForMissingStub: _FakeRandomAccessFile_5(
          this,
          Invocation.method(#openSync, [], {#mode: mode}),
        ),
      ) as _i2.RandomAccessFile);

  @override
  _i7.Stream<List<int>> openRead([int? start, int? end]) => (super.noSuchMethod(
        Invocation.method(#openRead, [start, end]),
        returnValue: _i7.Stream<List<int>>.empty(),
        returnValueForMissingStub: _i7.Stream<List<int>>.empty(),
      ) as _i7.Stream<List<int>>);

  @override
  _i2.IOSink openWrite({
    _i2.FileMode? mode = _i2.FileMode.write,
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(#openWrite, [], {
          #mode: mode,
          #encoding: encoding,
        }),
        returnValue: _FakeIOSink_6(
          this,
          Invocation.method(#openWrite, [], {
            #mode: mode,
            #encoding: encoding,
          }),
        ),
        returnValueForMissingStub: _FakeIOSink_6(
          this,
          Invocation.method(#openWrite, [], {
            #mode: mode,
            #encoding: encoding,
          }),
        ),
      ) as _i2.IOSink);

  @override
  _i7.Future<_i9.Uint8List> readAsBytes() => (super.noSuchMethod(
        Invocation.method(#readAsBytes, []),
        returnValue: _i7.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
        returnValueForMissingStub: _i7.Future<_i9.Uint8List>.value(
          _i9.Uint8List(0),
        ),
      ) as _i7.Future<_i9.Uint8List>);

  @override
  _i9.Uint8List readAsBytesSync() => (super.noSuchMethod(
        Invocation.method(#readAsBytesSync, []),
        returnValue: _i9.Uint8List(0),
        returnValueForMissingStub: _i9.Uint8List(0),
      ) as _i9.Uint8List);

  @override
  _i7.Future<String> readAsString({
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(#readAsString, [], {#encoding: encoding}),
        returnValue: _i7.Future<String>.value(
          _i6.dummyValue<String>(
            this,
            Invocation.method(#readAsString, [], {#encoding: encoding}),
          ),
        ),
        returnValueForMissingStub: _i7.Future<String>.value(
          _i6.dummyValue<String>(
            this,
            Invocation.method(#readAsString, [], {#encoding: encoding}),
          ),
        ),
      ) as _i7.Future<String>);

  @override
  String readAsStringSync({_i8.Encoding? encoding = const _i8.Utf8Codec()}) => (super.noSuchMethod(
        Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
        ),
      ) as String);

  @override
  _i7.Future<List<String>> readAsLines({
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(#readAsLines, [], {#encoding: encoding}),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i7.Future<List<String>>.value(
          <String>[],
        ),
      ) as _i7.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
        returnValue: <String>[],
        returnValueForMissingStub: <String>[],
      ) as List<String>);

  @override
  _i7.Future<_i2.File> writeAsBytes(
    List<int>? bytes, {
    _i2.FileMode? mode = _i2.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAsBytes,
          [bytes],
          {#mode: mode, #flush: flush},
        ),
        returnValue: _i7.Future<_i2.File>.value(
          _FakeFile_0(
            this,
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
          ),
        ),
        returnValueForMissingStub: _i7.Future<_i2.File>.value(
          _FakeFile_0(
            this,
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
          ),
        ),
      ) as _i7.Future<_i2.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i2.FileMode? mode = _i2.FileMode.write,
    bool? flush = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.File> writeAsString(
    String? contents, {
    _i2.FileMode? mode = _i2.FileMode.write,
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeAsString,
          [contents],
          {#mode: mode, #encoding: encoding, #flush: flush},
        ),
        returnValue: _i7.Future<_i2.File>.value(
          _FakeFile_0(
            this,
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
          ),
        ),
        returnValueForMissingStub: _i7.Future<_i2.File>.value(
          _FakeFile_0(
            this,
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
          ),
        ),
      ) as _i7.Future<_i2.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i2.FileMode? mode = _i2.FileMode.write,
    _i8.Encoding? encoding = const _i8.Utf8Codec(),
    bool? flush = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeAsStringSync,
          [contents],
          {#mode: mode, #encoding: encoding, #flush: flush},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> exists() => (super.noSuchMethod(
        Invocation.method(#exists, []),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  bool existsSync() => (super.noSuchMethod(
        Invocation.method(#existsSync, []),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<String> resolveSymbolicLinks() => (super.noSuchMethod(
        Invocation.method(#resolveSymbolicLinks, []),
        returnValue: _i7.Future<String>.value(
          _i6.dummyValue<String>(
            this,
            Invocation.method(#resolveSymbolicLinks, []),
          ),
        ),
        returnValueForMissingStub: _i7.Future<String>.value(
          _i6.dummyValue<String>(
            this,
            Invocation.method(#resolveSymbolicLinks, []),
          ),
        ),
      ) as _i7.Future<String>);

  @override
  String resolveSymbolicLinksSync() => (super.noSuchMethod(
        Invocation.method(#resolveSymbolicLinksSync, []),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(#resolveSymbolicLinksSync, []),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(#resolveSymbolicLinksSync, []),
        ),
      ) as String);

  @override
  _i7.Future<_i2.FileStat> stat() => (super.noSuchMethod(
        Invocation.method(#stat, []),
        returnValue: _i7.Future<_i2.FileStat>.value(
          _FakeFileStat_7(this, Invocation.method(#stat, [])),
        ),
        returnValueForMissingStub: _i7.Future<_i2.FileStat>.value(
          _FakeFileStat_7(this, Invocation.method(#stat, [])),
        ),
      ) as _i7.Future<_i2.FileStat>);

  @override
  _i2.FileStat statSync() => (super.noSuchMethod(
        Invocation.method(#statSync, []),
        returnValue: _FakeFileStat_7(
          this,
          Invocation.method(#statSync, []),
        ),
        returnValueForMissingStub: _FakeFileStat_7(
          this,
          Invocation.method(#statSync, []),
        ),
      ) as _i2.FileStat);

  @override
  _i7.Stream<_i2.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#watch, [], {
          #events: events,
          #recursive: recursive,
        }),
        returnValue: _i7.Stream<_i2.FileSystemEvent>.empty(),
        returnValueForMissingStub: _i7.Stream<_i2.FileSystemEvent>.empty(),
      ) as _i7.Stream<_i2.FileSystemEvent>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get displayName => (super.noSuchMethod(
        Invocation.getter(#displayName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#displayName),
        ),
      ) as String);

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  List<_i10.OAuthProviderType> get providers => (super.noSuchMethod(
        Invocation.getter(#providers),
        returnValue: <_i10.OAuthProviderType>[],
        returnValueForMissingStub: <_i10.OAuthProviderType>[],
      ) as List<_i10.OAuthProviderType>);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  DateTime get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: _FakeDateTime_4(this, Invocation.getter(#createdAt)),
        returnValueForMissingStub: _FakeDateTime_4(
          this,
          Invocation.getter(#createdAt),
        ),
      ) as DateTime);

  @override
  DateTime get lastSignInAt => (super.noSuchMethod(
        Invocation.getter(#lastSignInAt),
        returnValue: _FakeDateTime_4(
          this,
          Invocation.getter(#lastSignInAt),
        ),
        returnValueForMissingStub: _FakeDateTime_4(
          this,
          Invocation.getter(#lastSignInAt),
        ),
      ) as DateTime);

  @override
  _i3.$UserCopyWith<_i3.User> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$UserCopyWith_8<_i3.User>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$UserCopyWith_8<_i3.User>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i3.$UserCopyWith<_i3.User>);
}

/// A class which mocks [UuidGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuidGenerator extends _i1.Mock implements _i11.UuidGenerator {
  @override
  String generate() => (super.noSuchMethod(
        Invocation.method(#generate, []),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(#generate, []),
        ),
        returnValueForMissingStub: _i6.dummyValue<String>(
          this,
          Invocation.method(#generate, []),
        ),
      ) as String);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  @override
  bool isSignedIn() => (super.noSuchMethod(
        Invocation.method(#isSignedIn, []),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i7.Future<void> signInWithAnonymous() => (super.noSuchMethod(
        Invocation.method(#signInWithAnonymous, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> signInWithApple() => (super.noSuchMethod(
        Invocation.method(#signInWithApple, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(#signInWithGoogle, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithApple() => (super.noSuchMethod(
        Invocation.method(#linkWithApple, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithGoogle() => (super.noSuchMethod(
        Invocation.method(#linkWithGoogle, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithX() => (super.noSuchMethod(
        Invocation.method(#linkWithX, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithTwitch() => (super.noSuchMethod(
        Invocation.method(#linkWithTwitch, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithDiscord() => (super.noSuchMethod(
        Invocation.method(#linkWithDiscord, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(#signOut, []),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [StorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRepository extends _i1.Mock implements _i13.StorageRepository {
  @override
  _i7.Future<String> uploadFile({
    required _i14.StorageType? storageType,
    required String? path,
    required String? filename,
    required _i2.File? file,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#uploadFile, [], {
          #storageType: storageType,
          #path: path,
          #filename: filename,
          #file: file,
        }),
        returnValue: _i7.Future<String>.value(
          _i6.dummyValue<String>(
            this,
            Invocation.method(#uploadFile, [], {
              #storageType: storageType,
              #path: path,
              #filename: filename,
              #file: file,
            }),
          ),
        ),
        returnValueForMissingStub: _i7.Future<String>.value(
          _i6.dummyValue<String>(
            this,
            Invocation.method(#uploadFile, [], {
              #storageType: storageType,
              #path: path,
              #filename: filename,
              #file: file,
            }),
          ),
        ),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> deleteFile({
    required _i14.StorageType? storageType,
    required String? path,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#deleteFile, [], {
          #storageType: storageType,
          #path: path,
        }),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [TUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTUserRepository extends _i1.Mock implements _i15.TUserRepository {
  @override
  _i7.Future<_i4.TUser> findByPrimaryKey(String? id) => (super.noSuchMethod(
        Invocation.method(#findByPrimaryKey, [id]),
        returnValue: _i7.Future<_i4.TUser>.value(
          _FakeTUser_9(this, Invocation.method(#findByPrimaryKey, [id])),
        ),
        returnValueForMissingStub: _i7.Future<_i4.TUser>.value(
          _FakeTUser_9(this, Invocation.method(#findByPrimaryKey, [id])),
        ),
      ) as _i7.Future<_i4.TUser>);

  @override
  _i7.Future<_i4.TUser> findByGynxId(String? gynxId) => (super.noSuchMethod(
        Invocation.method(#findByGynxId, [gynxId]),
        returnValue: _i7.Future<_i4.TUser>.value(
          _FakeTUser_9(this, Invocation.method(#findByGynxId, [gynxId])),
        ),
        returnValueForMissingStub: _i7.Future<_i4.TUser>.value(
          _FakeTUser_9(this, Invocation.method(#findByGynxId, [gynxId])),
        ),
      ) as _i7.Future<_i4.TUser>);

  @override
  _i7.Future<bool> existsById(String? gynxId) => (super.noSuchMethod(
        Invocation.method(#existsById, [gynxId]),
        returnValue: _i7.Future<bool>.value(false),
        returnValueForMissingStub: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> updateByPrimaryKey({
    required String? id,
    required String? gynxId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#updateByPrimaryKey, [], {
          #id: id,
          #gynxId: gynxId,
        }),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [TUserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTUserProfileRepository extends _i1.Mock implements _i16.TUserProfileRepository {
  @override
  _i7.Future<_i5.TUserProfile> findByPrimaryKey(String? userId) => (super.noSuchMethod(
        Invocation.method(#findByPrimaryKey, [userId]),
        returnValue: _i7.Future<_i5.TUserProfile>.value(
          _FakeTUserProfile_10(
            this,
            Invocation.method(#findByPrimaryKey, [userId]),
          ),
        ),
        returnValueForMissingStub: _i7.Future<_i5.TUserProfile>.value(
          _FakeTUserProfile_10(
            this,
            Invocation.method(#findByPrimaryKey, [userId]),
          ),
        ),
      ) as _i7.Future<_i5.TUserProfile>);

  @override
  _i7.Future<void> updateByPrimaryKeySelective({
    required String? userId,
    required String? username,
    required String? avatarUrl,
    bool? isDeleteAvatarUrl = false,
    required String? selfIntroduction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(#updateByPrimaryKeySelective, [], {
          #userId: userId,
          #username: username,
          #avatarUrl: avatarUrl,
          #isDeleteAvatarUrl: isDeleteAvatarUrl,
          #selfIntroduction: selfIntroduction,
        }),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
