// Mocks generated by Mockito 5.4.5 from annotations
// in app/test/src/presentation/pages/home/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:app/src/domain/entities/v_user.dart' as _i3;
import 'package:app/src/domain/models/suite_user.dart' as _i4;
import 'package:app/src/domain/models/v_post_list.dart' as _i2;
import 'package:app/src/domain/usecases/fetch_post_usecase.dart' as _i5;
import 'package:app/src/domain/usecases/find_user_usecase.dart' as _i7;
import 'package:app/src/domain/usecases/suite_user_usecase.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVPostList_0 extends _i1.SmartFake implements _i2.VPostList {
  _FakeVPostList_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeVUser_1 extends _i1.SmartFake implements _i3.VUser {
  _FakeVUser_1(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

class _FakeSuiteUser_2 extends _i1.SmartFake implements _i4.SuiteUser {
  _FakeSuiteUser_2(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [FetchPostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchPostUseCase extends _i1.Mock implements _i5.FetchPostUseCase {
  @override
  _i6.Future<_i2.VPostList> execute({int? sincePostId, int? maxPostId}) => (super.noSuchMethod(
        Invocation.method(#execute, [], {
          #sincePostId: sincePostId,
          #maxPostId: maxPostId,
        }),
        returnValue: _i6.Future<_i2.VPostList>.value(
          _FakeVPostList_0(
            this,
            Invocation.method(#execute, [], {
              #sincePostId: sincePostId,
              #maxPostId: maxPostId,
            }),
          ),
        ),
        returnValueForMissingStub: _i6.Future<_i2.VPostList>.value(
          _FakeVPostList_0(
            this,
            Invocation.method(#execute, [], {
              #sincePostId: sincePostId,
              #maxPostId: maxPostId,
            }),
          ),
        ),
      ) as _i6.Future<_i2.VPostList>);
}

/// A class which mocks [FindUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFindUserUseCase extends _i1.Mock implements _i7.FindUserUseCase {
  @override
  _i6.Future<_i3.VUser> execute(String? userId) => (super.noSuchMethod(
        Invocation.method(#execute, [userId]),
        returnValue: _i6.Future<_i3.VUser>.value(
          _FakeVUser_1(this, Invocation.method(#execute, [userId])),
        ),
        returnValueForMissingStub: _i6.Future<_i3.VUser>.value(
          _FakeVUser_1(this, Invocation.method(#execute, [userId])),
        ),
      ) as _i6.Future<_i3.VUser>);
}

/// A class which mocks [SuiteUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuiteUserUseCase extends _i1.Mock implements _i8.SuiteUserUseCase {
  @override
  _i6.Future<_i4.SuiteUser> execute() => (super.noSuchMethod(
        Invocation.method(#execute, []),
        returnValue: _i6.Future<_i4.SuiteUser>.value(
          _FakeSuiteUser_2(this, Invocation.method(#execute, [])),
        ),
        returnValueForMissingStub: _i6.Future<_i4.SuiteUser>.value(
          _FakeSuiteUser_2(this, Invocation.method(#execute, [])),
        ),
      ) as _i6.Future<_i4.SuiteUser>);
}
