name: rls
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:

dev_dependencies:
  faker: 2.2.0
  gynx_constants:
    path: ../../packages/gynx_constants
  lints: 5.1.1
  test: 1.25.15
  supabase: 2.6.3
  pedantic_mono: any
