name: rls
version: 0.0.0
publish_to: none
environment:
  sdk: ^3.6.0
dev_dependencies:
  config:
    path: ../../packages/config
  faker: 2.2.0
  lints: 6.0.0
  pedantic_mono: any
  supabase: 2.6.3
  test: 1.25.15
resolution: workspace
