include: package:pedantic_mono/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - '**/*.mocks.dart'
  errors:
    lines_longer_than_80_chars: ignore
    avoid_classes_with_only_static_members: ignore
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
