include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - '**/*.mocks.dart'
  errors:
    avoid_classes_with_only_static_members: ignore
    invalid_annotation_target: ignore
