# Visit https://melos.invertase.dev/configuration/overview for more information about this configuration file

name: gynx

packages:
  - apps/**
  - packages/**

command:
  version:
    # # Only allow versioning to happen on main branch.
    # branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
  bootstrap:
    usePubspecOverrides:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    environment:
      sdk: ">=3.3.0 <4.0.0"
    dependencies:
      collection: 1.18.0
      riverpod: 2.6.1
      flutter_riverpod: 2.6.1
      riverpod_annotation: 2.6.1
      google_fonts: 6.2.1
    dev_dependencies:
      test: 1.25.9
      pedantic_mono: any
      lint: 2.3.0
      lints: 5.0.0
      flutter_lints: 5.0.0
      build_runner: 2.4.13
      riverpod_generator: 2.6.3
  ide:
    intellij: true
scripts:
  analyze: melos exec --fail-fast -- "dart analyze ."
  analyze-fix: melos exec --fail-fast -- "dart fix --apply"
