# Visit https://melos.invertase.dev/configuration/overview for more information about this configuration file

name: gynx

packages:
  - apps/**
  - packages/**

command:
  version:
    # # Only allow versioning to happen on main branch.
    # branch: master
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
  bootstrap:
    usePubspecOverrides:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
    environment:
      sdk: ">=3.3.0 <4.0.0"
      flutter: ">=1.17.0"
    dependencies:
      collection: 1.18.0
      firebase_core: 3.8.0
      firebase_auth: 5.3.3
      firebase_crashlytics: 4.1.5
      firebase_analytics: 11.3.5
      freezed_annotation: 2.4.4
      riverpod: 2.6.1
      flutter_riverpod: 2.6.1
      riverpod_annotation: 2.6.1
      google_fonts: 6.2.1
      flutter_clean_architecture: 6.0.1
      get_it: 8.0.2
      injectable: 2.5.0
      intl: 0.19.0
    dev_dependencies:
      test: 1.25.7
      mockito: 5.4.4
      pedantic_mono: any
      lint: 2.3.0
      lints: 5.0.0
      flutter_lints: 5.0.0
      build_runner: 2.4.13
      riverpod_generator: 2.6.3
      injectable_generator: 2.6.2
  ide:
    intellij: true
scripts:
  gen: melos exec --ignore='gynx_app' --fail-fast -- "dart run build_runner build --delete-conflicting-outputs"
  gen-l10n: melos exec --scope='gynx_l10n' -- flutter gen-l10n
  fix: melos exec --fail-fast -- "dart fix --apply ."
