name: Gynx
version: 0.0.0
publish_to: none
environment:
  sdk: ^3.6.0
  flutter: ^3.29.1
dev_dependencies:
  custom_lint: 0.7.5
  melos: 7.0.0-dev.8
  pedantic_mono: 1.30.3
  pubspec_dependency_sorter: 1.0.5
  riverpod_lint: 2.6.5
workspace:
  - apps/app
  - packages/components
  - packages/config
  - packages/locales
  - supabase/rls
melos:
  scripts:
    pubspec-sort: melos exec -- "dart run pubspec_dependency_sorter"
    gen: melos exec --ignore='locales' --ignore='rls' --fail-fast -- "dart run build_runner build --delete-conflicting-outputs"
    gen-config: melos exec --scope='config' -- "dart run build_runner build --delete-conflicting-outputs"
    gen-l10n: melos exec --scope='locales' -- flutter gen-l10n
    fix: melos exec --fail-fast -- "dart fix --apply ."
    format: melos format --ignore='locales'
    analyze: melos exec --fail-fast -- "dart analyze ."
    test: melos exec --ignore='components' --ignore='config' --ignore='locales' --ignore='rls' --fail-fast -- "flutter test"
    rls-test: melos exec --scope='rls' --fail-fast -- "flutter test"
    supabase-start: supabase start
    supabase-stop: supabase stop
  command:
    version:
      workspaceChangelog: true
    bootstrap:
      usePubspecOverrides: null
      runPubGetInParallel: false
      environment:
        sdk: ^3.6.0
        flutter: ^3.29.1
    ide:
      intellij: true
