// Mocks generated by Mockito 5.4.5 from annotations
// in app/test/src/presentation/pages/home/components/form_builder_image_picker_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i9;
import 'dart:typed_data' as _i10;

import 'package:app/src/presentation/dialogs/alert.dart' as _i7;
import 'package:app/src/presentation/dialogs/loading_dialog.dart' as _i3;
import 'package:flutter_video_info/flutter_video_info.dart' as _i6;
import 'package:image_picker/image_picker.dart' as _i4;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLostDataResponse_0 extends _i1.SmartFake
    implements _i2.LostDataResponse {
  _FakeLostDataResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoadingDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadingDialog extends _i1.Mock implements _i3.LoadingDialog {
  @override
  void show() => super.noSuchMethod(
    Invocation.method(#show, []),
    returnValueForMissingStub: null,
  );

  @override
  void hide() => super.noSuchMethod(
    Invocation.method(#hide, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i4.ImagePicker {
  @override
  _i5.Future<_i2.XFile?> pickImage({
    required _i2.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i2.CameraDevice? preferredCameraDevice = _i2.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [], {
              #source: source,
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #preferredCameraDevice: preferredCameraDevice,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i5.Future<_i2.XFile?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.XFile?>.value(),
          )
          as _i5.Future<_i2.XFile?>);

  @override
  _i5.Future<List<_i2.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiImage, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i5.Future<List<_i2.XFile>>.value(<_i2.XFile>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.XFile>>.value(
              <_i2.XFile>[],
            ),
          )
          as _i5.Future<List<_i2.XFile>>);

  @override
  _i5.Future<_i2.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i5.Future<_i2.XFile?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.XFile?>.value(),
          )
          as _i5.Future<_i2.XFile?>);

  @override
  _i5.Future<List<_i2.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultipleMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i5.Future<List<_i2.XFile>>.value(<_i2.XFile>[]),
            returnValueForMissingStub: _i5.Future<List<_i2.XFile>>.value(
              <_i2.XFile>[],
            ),
          )
          as _i5.Future<List<_i2.XFile>>);

  @override
  _i5.Future<_i2.XFile?> pickVideo({
    required _i2.ImageSource? source,
    _i2.CameraDevice? preferredCameraDevice = _i2.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideo, [], {
              #source: source,
              #preferredCameraDevice: preferredCameraDevice,
              #maxDuration: maxDuration,
            }),
            returnValue: _i5.Future<_i2.XFile?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.XFile?>.value(),
          )
          as _i5.Future<_i2.XFile?>);

  @override
  _i5.Future<_i2.LostDataResponse> retrieveLostData() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveLostData, []),
            returnValue: _i5.Future<_i2.LostDataResponse>.value(
              _FakeLostDataResponse_0(
                this,
                Invocation.method(#retrieveLostData, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.LostDataResponse>.value(
              _FakeLostDataResponse_0(
                this,
                Invocation.method(#retrieveLostData, []),
              ),
            ),
          )
          as _i5.Future<_i2.LostDataResponse>);

  @override
  bool supportsImageSource(_i2.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#supportsImageSource, [source]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [FlutterVideoInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterVideoInfo extends _i1.Mock implements _i6.FlutterVideoInfo {
  @override
  _i5.Future<_i6.VideoData?> getVideoInfo(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoInfo, [path]),
            returnValue: _i5.Future<_i6.VideoData?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.VideoData?>.value(),
          )
          as _i5.Future<_i6.VideoData?>);
}

/// A class which mocks [VideoData].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoData extends _i1.Mock implements _i6.VideoData {
  @override
  set path(String? _path) => super.noSuchMethod(
    Invocation.setter(#path, _path),
    returnValueForMissingStub: null,
  );

  @override
  set title(String? _title) => super.noSuchMethod(
    Invocation.setter(#title, _title),
    returnValueForMissingStub: null,
  );

  @override
  set author(String? _author) => super.noSuchMethod(
    Invocation.setter(#author, _author),
    returnValueForMissingStub: null,
  );

  @override
  set mimetype(String? _mimetype) => super.noSuchMethod(
    Invocation.setter(#mimetype, _mimetype),
    returnValueForMissingStub: null,
  );

  @override
  set date(String? _date) => super.noSuchMethod(
    Invocation.setter(#date, _date),
    returnValueForMissingStub: null,
  );

  @override
  set location(String? _location) => super.noSuchMethod(
    Invocation.setter(#location, _location),
    returnValueForMissingStub: null,
  );

  @override
  set framerate(double? _framerate) => super.noSuchMethod(
    Invocation.setter(#framerate, _framerate),
    returnValueForMissingStub: null,
  );

  @override
  set width(int? _width) => super.noSuchMethod(
    Invocation.setter(#width, _width),
    returnValueForMissingStub: null,
  );

  @override
  set height(int? _height) => super.noSuchMethod(
    Invocation.setter(#height, _height),
    returnValueForMissingStub: null,
  );

  @override
  set orientation(int? _orientation) => super.noSuchMethod(
    Invocation.setter(#orientation, _orientation),
    returnValueForMissingStub: null,
  );

  @override
  set filesize(int? _filesize) => super.noSuchMethod(
    Invocation.setter(#filesize, _filesize),
    returnValueForMissingStub: null,
  );

  @override
  set duration(double? _duration) => super.noSuchMethod(
    Invocation.setter(#duration, _duration),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Alert].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlert extends _i1.Mock implements _i7.Alert {
  @override
  _i5.Future<void> showInfo({required String? title, required String? text}) =>
      (super.noSuchMethod(
            Invocation.method(#showInfo, [], {#title: title, #text: text}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i7.AlertResultType> showAlert({
    required String? title,
    required String? text,
    required String? leftButtonText,
    required String? rightButtonText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showAlert, [], {
              #title: title,
              #text: text,
              #leftButtonText: leftButtonText,
              #rightButtonText: rightButtonText,
            }),
            returnValue: _i5.Future<_i7.AlertResultType>.value(
              _i7.AlertResultType.left,
            ),
            returnValueForMissingStub: _i5.Future<_i7.AlertResultType>.value(
              _i7.AlertResultType.left,
            ),
          )
          as _i5.Future<_i7.AlertResultType>);

  @override
  _i5.Future<_i7.ActionSheetResultType> showActionSheet({
    String? title,
    String? message,
    required String? positiveButtonText,
    required String? neutralButtonText,
    required String? negativeButtonText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showActionSheet, [], {
              #title: title,
              #message: message,
              #positiveButtonText: positiveButtonText,
              #neutralButtonText: neutralButtonText,
              #negativeButtonText: negativeButtonText,
            }),
            returnValue: _i5.Future<_i7.ActionSheetResultType>.value(
              _i7.ActionSheetResultType.positive,
            ),
            returnValueForMissingStub:
                _i5.Future<_i7.ActionSheetResultType>.value(
                  _i7.ActionSheetResultType.positive,
                ),
          )
          as _i5.Future<_i7.ActionSheetResultType>);
}

/// A class which mocks [XFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockXFile extends _i1.Mock implements _i2.XFile {
  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#path)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i5.Future<void> saveTo(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#saveTo, [path]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i5.Future<int>.value(0),
            returnValueForMissingStub: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<String> readAsString({
    _i9.Encoding? encoding = const _i9.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
            returnValueForMissingStub: _i5.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i10.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i5.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
            returnValueForMissingStub: _i5.Future<_i10.Uint8List>.value(
              _i10.Uint8List(0),
            ),
          )
          as _i5.Future<_i10.Uint8List>);

  @override
  _i5.Stream<_i10.Uint8List> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i5.Stream<_i10.Uint8List>.empty(),
            returnValueForMissingStub: _i5.Stream<_i10.Uint8List>.empty(),
          )
          as _i5.Stream<_i10.Uint8List>);

  @override
  _i5.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i5.Future<DateTime>.value(
              _FakeDateTime_1(this, Invocation.method(#lastModified, [])),
            ),
            returnValueForMissingStub: _i5.Future<DateTime>.value(
              _FakeDateTime_1(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i5.Future<DateTime>);
}
