// Mocks generated by Mockito 5.4.5 from annotations
// in gynx_app/test/src/presentation/pages/sign_in/sign_in_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gynx_app/src/domain/enums/oauth_provider_type.dart' as _i4;
import 'package:gynx_app/src/domain/usecases/sign_in_with_anonymous_usecase.dart'
    as _i5;
import 'package:gynx_app/src/domain/usecases/sign_in_with_oauth_usecase.dart'
    as _i2;
import 'package:gynx_app/src/presentation/dialogs/alert.dart' as _i8;
import 'package:gynx_app/src/presentation/dialogs/loading_dialog.dart' as _i6;
import 'package:gynx_app/src/presentation/dialogs/notify.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SignInWithOAuthUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithOAuthUseCase extends _i1.Mock
    implements _i2.SignInWithOAuthUseCase {
  @override
  _i3.Future<void> execute(_i4.OAuthProviderType? oauthProviderType) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [oauthProviderType]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SignInWithAnonymousUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithAnonymousUseCase extends _i1.Mock
    implements _i5.SignInWithAnonymousUseCase {
  @override
  _i3.Future<void> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [LoadingDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadingDialog extends _i1.Mock implements _i6.LoadingDialog {
  @override
  void show() => super.noSuchMethod(
    Invocation.method(#show, []),
    returnValueForMissingStub: null,
  );

  @override
  void hide() => super.noSuchMethod(
    Invocation.method(#hide, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Notify].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotify extends _i1.Mock implements _i7.Notify {
  @override
  void showError({required String? message}) => super.noSuchMethod(
    Invocation.method(#showError, [], {#message: message}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Alert].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlert extends _i1.Mock implements _i8.Alert {
  @override
  _i3.Future<void> showInfo({required String? title, required String? text}) =>
      (super.noSuchMethod(
            Invocation.method(#showInfo, [], {#title: title, #text: text}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i8.AlertResultType> showAlert({
    required String? title,
    required String? text,
    required String? leftButtonText,
    required String? rightButtonText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showAlert, [], {
              #title: title,
              #text: text,
              #leftButtonText: leftButtonText,
              #rightButtonText: rightButtonText,
            }),
            returnValue: _i3.Future<_i8.AlertResultType>.value(
              _i8.AlertResultType.left,
            ),
            returnValueForMissingStub: _i3.Future<_i8.AlertResultType>.value(
              _i8.AlertResultType.left,
            ),
          )
          as _i3.Future<_i8.AlertResultType>);

  @override
  _i3.Future<_i8.ActionSheetResultType> showActionSheet({
    String? title,
    String? message,
    required String? positiveButtonText,
    required String? neutralButtonText,
    required String? negativeButtonText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showActionSheet, [], {
              #title: title,
              #message: message,
              #positiveButtonText: positiveButtonText,
              #neutralButtonText: neutralButtonText,
              #negativeButtonText: negativeButtonText,
            }),
            returnValue: _i3.Future<_i8.ActionSheetResultType>.value(
              _i8.ActionSheetResultType.positive,
            ),
            returnValueForMissingStub:
                _i3.Future<_i8.ActionSheetResultType>.value(
                  _i8.ActionSheetResultType.positive,
                ),
          )
          as _i3.Future<_i8.ActionSheetResultType>);
}
