// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/presentation/pages/sign_in/sign_in_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i6;
import 'package:gynx_app/src/presentation/navigation/page_navigator.dart'
    as _i5;
import 'package:gynx_app/src/presentation/navigation/page_type.dart' as _i7;
import 'package:gynx_app/src/presentation/pages/sign_in/sign_in_controller.dart'
    as _i2;
import 'package:gynx_l10n/gynx_l10n.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SignInController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInController extends _i1.Mock implements _i2.SignInController {
  @override
  _i3.Future<void> signInWithApple(_i4.L10n? l10n) => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [l10n],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithGoogle(_i4.L10n? l10n) => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [l10n],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signInWithAnonymous(_i4.L10n? l10n) => (super.noSuchMethod(
        Invocation.method(
          #signInWithAnonymous,
          [l10n],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [PageNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockPageNavigator extends _i1.Mock implements _i5.PageNavigator {
  @override
  void pop<T extends Object?>(
    _i6.BuildContext? context, [
    T? result,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #pop,
          [
            context,
            result,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void push(
    _i6.BuildContext? context,
    _i7.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #push,
          [
            context,
            pageType,
          ],
          {
            #pathParams: pathParams,
            #queryParams: queryParams,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void go(
    _i6.BuildContext? context,
    _i7.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #go,
          [
            context,
            pageType,
          ],
          {
            #pathParams: pathParams,
            #queryParams: queryParams,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushReplacement(
    _i6.BuildContext? context,
    _i7.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #pushReplacement,
          [
            context,
            pageType,
          ],
          {
            #pathParams: pathParams,
            #queryParams: queryParams,
          },
        ),
        returnValueForMissingStub: null,
      );
}
