// Mocks generated by Mockito 5.4.5 from annotations
// in app/test/src/presentation/pages/edit_profile/components/edit_screen_name_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:app/src/domain/models/suite_user.dart' as _i2;
import 'package:app/src/domain/usecases/check_screen_name_existence_usecase.dart'
    as _i9;
import 'package:app/src/domain/usecases/suite_user_usecase.dart' as _i7;
import 'package:app/src/presentation/dialogs/loading_dialog.dart' as _i3;
import 'package:app/src/presentation/navigation/page_navigator.dart' as _i4;
import 'package:app/src/presentation/navigation/page_type.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSuiteUser_0 extends _i1.SmartFake implements _i2.SuiteUser {
  _FakeSuiteUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoadingDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadingDialog extends _i1.Mock implements _i3.LoadingDialog {
  @override
  void show() => super.noSuchMethod(
    Invocation.method(#show, []),
    returnValueForMissingStub: null,
  );

  @override
  void hide() => super.noSuchMethod(
    Invocation.method(#hide, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PageNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockPageNavigator extends _i1.Mock implements _i4.PageNavigator {
  @override
  void pop<T extends Object?>(_i5.BuildContext? context, [T? result]) =>
      super.noSuchMethod(
        Invocation.method(#pop, [context, result]),
        returnValueForMissingStub: null,
      );

  @override
  void push(
    _i5.BuildContext? context,
    _i6.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) => super.noSuchMethod(
    Invocation.method(
      #push,
      [context, pageType],
      {#pathParams: pathParams, #queryParams: queryParams},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void go(
    _i5.BuildContext? context,
    _i6.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) => super.noSuchMethod(
    Invocation.method(
      #go,
      [context, pageType],
      {#pathParams: pathParams, #queryParams: queryParams},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void pushReplacement(
    _i5.BuildContext? context,
    _i6.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) => super.noSuchMethod(
    Invocation.method(
      #pushReplacement,
      [context, pageType],
      {#pathParams: pathParams, #queryParams: queryParams},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SuiteUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuiteUserUseCase extends _i1.Mock implements _i7.SuiteUserUseCase {
  @override
  _i8.Future<_i2.SuiteUser> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i8.Future<_i2.SuiteUser>.value(
              _FakeSuiteUser_0(this, Invocation.method(#execute, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i2.SuiteUser>.value(
              _FakeSuiteUser_0(this, Invocation.method(#execute, [])),
            ),
          )
          as _i8.Future<_i2.SuiteUser>);
}

/// A class which mocks [CheckScreenNameExistenceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckScreenNameExistenceUseCase extends _i1.Mock
    implements _i9.CheckScreenNameExistenceUseCase {
  @override
  _i8.Future<bool> execute(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [screenName]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}
