// Mocks generated by Mockito 5.4.5 from annotations
// in gynx_app/test/src/application/interactors/create_post_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i10;

import 'package:gynx_app/src/domain/entities/v_post.dart' as _i2;
import 'package:gynx_app/src/domain/enums/storage_type.dart' as _i9;
import 'package:gynx_app/src/domain/enums/timeline_type.dart' as _i12;
import 'package:gynx_app/src/domain/generators/uuid_generator.dart' as _i4;
import 'package:gynx_app/src/domain/models/media_list.dart' as _i13;
import 'package:gynx_app/src/domain/models/post_id_list.dart' as _i15;
import 'package:gynx_app/src/domain/models/v_post_list.dart' as _i3;
import 'package:gynx_app/src/domain/repositories/auth_repository.dart' as _i6;
import 'package:gynx_app/src/domain/repositories/post_repository.dart' as _i11;
import 'package:gynx_app/src/domain/repositories/storage_repository.dart'
    as _i8;
import 'package:gynx_app/src/domain/repositories/v_post_repository.dart'
    as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVPost_0 extends _i1.SmartFake implements _i2.VPost {
  _FakeVPost_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVPostList_1 extends _i1.SmartFake implements _i3.VPostList {
  _FakeVPostList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UuidGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuidGenerator extends _i1.Mock implements _i4.UuidGenerator {
  @override
  String generate() =>
      (super.noSuchMethod(
            Invocation.method(#generate, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#generate, []),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.method(#generate, []),
            ),
          )
          as String);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  @override
  bool isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<void> signInWithAnonymous() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithAnonymous, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#linkWithApple, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#linkWithGoogle, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithX() =>
      (super.noSuchMethod(
            Invocation.method(#linkWithX, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithTwitch() =>
      (super.noSuchMethod(
            Invocation.method(#linkWithTwitch, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> linkWithDiscord() =>
      (super.noSuchMethod(
            Invocation.method(#linkWithDiscord, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [StorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRepository extends _i1.Mock implements _i8.StorageRepository {
  @override
  _i7.Future<String> uploadFile({
    required _i9.StorageType? storageType,
    required String? path,
    required String? filename,
    required _i10.File? file,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [], {
              #storageType: storageType,
              #path: path,
              #filename: filename,
              #file: file,
            }),
            returnValue: _i7.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#uploadFile, [], {
                  #storageType: storageType,
                  #path: path,
                  #filename: filename,
                  #file: file,
                }),
              ),
            ),
            returnValueForMissingStub: _i7.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#uploadFile, [], {
                  #storageType: storageType,
                  #path: path,
                  #filename: filename,
                  #file: file,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> deleteFile({
    required _i9.StorageType? storageType,
    required String? path,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [], {
              #storageType: storageType,
              #path: path,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i11.PostRepository {
  @override
  _i7.Future<int> create(
    _i12.TimelineType? timelineType,
    String? text,
    _i13.MediaList? mediaList,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [timelineType, text, mediaList]),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);
}

/// A class which mocks [VPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVPostRepository extends _i1.Mock implements _i14.VPostRepository {
  @override
  _i7.Future<_i2.VPost> findByPostId(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#findByPostId, [postId]),
            returnValue: _i7.Future<_i2.VPost>.value(
              _FakeVPost_0(this, Invocation.method(#findByPostId, [postId])),
            ),
            returnValueForMissingStub: _i7.Future<_i2.VPost>.value(
              _FakeVPost_0(this, Invocation.method(#findByPostId, [postId])),
            ),
          )
          as _i7.Future<_i2.VPost>);

  @override
  _i7.Future<_i3.VPostList> findByPostIdList(_i15.PostIdList? postIdList) =>
      (super.noSuchMethod(
            Invocation.method(#findByPostIdList, [postIdList]),
            returnValue: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByPostIdList, [postIdList]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByPostIdList, [postIdList]),
              ),
            ),
          )
          as _i7.Future<_i3.VPostList>);

  @override
  _i7.Future<_i3.VPostList> findByLatest(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#findByLatest, [count]),
            returnValue: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(this, Invocation.method(#findByLatest, [count])),
            ),
            returnValueForMissingStub: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(this, Invocation.method(#findByLatest, [count])),
            ),
          )
          as _i7.Future<_i3.VPostList>);

  @override
  _i7.Future<_i3.VPostList> findBySincePostId(int? sincePostId, int? count) =>
      (super.noSuchMethod(
            Invocation.method(#findBySincePostId, [sincePostId, count]),
            returnValue: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findBySincePostId, [sincePostId, count]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findBySincePostId, [sincePostId, count]),
              ),
            ),
          )
          as _i7.Future<_i3.VPostList>);

  @override
  _i7.Future<_i3.VPostList> findByMaxPostId(int? maxPostId, int? count) =>
      (super.noSuchMethod(
            Invocation.method(#findByMaxPostId, [maxPostId, count]),
            returnValue: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByMaxPostId, [maxPostId, count]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByMaxPostId, [maxPostId, count]),
              ),
            ),
          )
          as _i7.Future<_i3.VPostList>);

  @override
  _i7.Future<_i3.VPostList> findByUserIdAndLatest(String? userId, int? count) =>
      (super.noSuchMethod(
            Invocation.method(#findByUserIdAndLatest, [userId, count]),
            returnValue: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndLatest, [userId, count]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndLatest, [userId, count]),
              ),
            ),
          )
          as _i7.Future<_i3.VPostList>);

  @override
  _i7.Future<_i3.VPostList> findByUserIdAndSincePostId(
    String? userId,
    int? sincePostId,
    int? count,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findByUserIdAndSincePostId, [
              userId,
              sincePostId,
              count,
            ]),
            returnValue: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndSincePostId, [
                  userId,
                  sincePostId,
                  count,
                ]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndSincePostId, [
                  userId,
                  sincePostId,
                  count,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.VPostList>);

  @override
  _i7.Future<_i3.VPostList> findByUserIdAndMaxPostId(
    String? userId,
    int? maxPostId,
    int? count,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findByUserIdAndMaxPostId, [
              userId,
              maxPostId,
              count,
            ]),
            returnValue: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndMaxPostId, [
                  userId,
                  maxPostId,
                  count,
                ]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndMaxPostId, [
                  userId,
                  maxPostId,
                  count,
                ]),
              ),
            ),
          )
          as _i7.Future<_i3.VPostList>);
}
