// Mocks generated by Mockito 5.4.5 from annotations
// in gynx_app/test/src/application/interactors/fetch_post_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:gynx_app/src/domain/entities/v_post.dart' as _i2;
import 'package:gynx_app/src/domain/models/post_id_list.dart' as _i6;
import 'package:gynx_app/src/domain/models/v_post_list.dart' as _i3;
import 'package:gynx_app/src/domain/repositories/v_post_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVPost_0 extends _i1.SmartFake implements _i2.VPost {
  _FakeVPost_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVPostList_1 extends _i1.SmartFake implements _i3.VPostList {
  _FakeVPostList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVPostRepository extends _i1.Mock implements _i4.VPostRepository {
  @override
  _i5.Future<_i2.VPost> findByPostId(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#findByPostId, [postId]),
            returnValue: _i5.Future<_i2.VPost>.value(
              _FakeVPost_0(this, Invocation.method(#findByPostId, [postId])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.VPost>.value(
              _FakeVPost_0(this, Invocation.method(#findByPostId, [postId])),
            ),
          )
          as _i5.Future<_i2.VPost>);

  @override
  _i5.Future<_i3.VPostList> findByPostIdList(_i6.PostIdList? postIdList) =>
      (super.noSuchMethod(
            Invocation.method(#findByPostIdList, [postIdList]),
            returnValue: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByPostIdList, [postIdList]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByPostIdList, [postIdList]),
              ),
            ),
          )
          as _i5.Future<_i3.VPostList>);

  @override
  _i5.Future<_i3.VPostList> findByLatest(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#findByLatest, [count]),
            returnValue: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(this, Invocation.method(#findByLatest, [count])),
            ),
            returnValueForMissingStub: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(this, Invocation.method(#findByLatest, [count])),
            ),
          )
          as _i5.Future<_i3.VPostList>);

  @override
  _i5.Future<_i3.VPostList> findBySincePostId(int? sincePostId, int? count) =>
      (super.noSuchMethod(
            Invocation.method(#findBySincePostId, [sincePostId, count]),
            returnValue: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findBySincePostId, [sincePostId, count]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findBySincePostId, [sincePostId, count]),
              ),
            ),
          )
          as _i5.Future<_i3.VPostList>);

  @override
  _i5.Future<_i3.VPostList> findByMaxPostId(int? maxPostId, int? count) =>
      (super.noSuchMethod(
            Invocation.method(#findByMaxPostId, [maxPostId, count]),
            returnValue: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByMaxPostId, [maxPostId, count]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByMaxPostId, [maxPostId, count]),
              ),
            ),
          )
          as _i5.Future<_i3.VPostList>);

  @override
  _i5.Future<_i3.VPostList> findByUserIdAndLatest(String? userId, int? count) =>
      (super.noSuchMethod(
            Invocation.method(#findByUserIdAndLatest, [userId, count]),
            returnValue: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndLatest, [userId, count]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndLatest, [userId, count]),
              ),
            ),
          )
          as _i5.Future<_i3.VPostList>);

  @override
  _i5.Future<_i3.VPostList> findByUserIdAndSincePostId(
    String? userId,
    int? sincePostId,
    int? count,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findByUserIdAndSincePostId, [
              userId,
              sincePostId,
              count,
            ]),
            returnValue: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndSincePostId, [
                  userId,
                  sincePostId,
                  count,
                ]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndSincePostId, [
                  userId,
                  sincePostId,
                  count,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.VPostList>);

  @override
  _i5.Future<_i3.VPostList> findByUserIdAndMaxPostId(
    String? userId,
    int? maxPostId,
    int? count,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findByUserIdAndMaxPostId, [
              userId,
              maxPostId,
              count,
            ]),
            returnValue: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndMaxPostId, [
                  userId,
                  maxPostId,
                  count,
                ]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.VPostList>.value(
              _FakeVPostList_1(
                this,
                Invocation.method(#findByUserIdAndMaxPostId, [
                  userId,
                  maxPostId,
                  count,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.VPostList>);
}
