// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/application/interactors/fetch_user_post_favorite_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:gynx_app/src/domain/entities/t_user_post_favorite.dart' as _i2;
import 'package:gynx_app/src/domain/entities/v_post.dart' as _i4;
import 'package:gynx_app/src/domain/models/post_id_list.dart' as _i9;
import 'package:gynx_app/src/domain/models/t_user_post_favorite_list.dart'
    as _i3;
import 'package:gynx_app/src/domain/models/v_post_list.dart' as _i5;
import 'package:gynx_app/src/domain/repositories/t_user_post_favorite_repository.dart'
    as _i6;
import 'package:gynx_app/src/domain/repositories/v_post_repository.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTUserPostFavorite_0 extends _i1.SmartFake
    implements _i2.TUserPostFavorite {
  _FakeTUserPostFavorite_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTUserPostFavoriteList_1 extends _i1.SmartFake
    implements _i3.TUserPostFavoriteList {
  _FakeTUserPostFavoriteList_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVPost_2 extends _i1.SmartFake implements _i4.VPost {
  _FakeVPost_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVPostList_3 extends _i1.SmartFake implements _i5.VPostList {
  _FakeVPostList_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TUserPostFavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTUserPostFavoriteRepository extends _i1.Mock
    implements _i6.TUserPostFavoriteRepository {
  @override
  _i7.Future<void> create(_i2.TUserPostFavorite? tPostFavorite) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [tPostFavorite],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.TUserPostFavorite> findByPrimaryKey(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByPrimaryKey,
          [id],
        ),
        returnValue:
            _i7.Future<_i2.TUserPostFavorite>.value(_FakeTUserPostFavorite_0(
          this,
          Invocation.method(
            #findByPrimaryKey,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.TUserPostFavorite>.value(_FakeTUserPostFavorite_0(
          this,
          Invocation.method(
            #findByPrimaryKey,
            [id],
          ),
        )),
      ) as _i7.Future<_i2.TUserPostFavorite>);

  @override
  _i7.Future<_i3.TUserPostFavoriteList> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByUserId,
            [userId],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByUserId,
            [userId],
          ),
        )),
      ) as _i7.Future<_i3.TUserPostFavoriteList>);

  @override
  _i7.Future<_i3.TUserPostFavoriteList> findByPostId(int? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByPostId,
          [postId],
        ),
        returnValue: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByPostId,
            [postId],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByPostId,
            [postId],
          ),
        )),
      ) as _i7.Future<_i3.TUserPostFavoriteList>);

  @override
  _i7.Future<_i3.TUserPostFavoriteList> findByUserIdAndLatest(
    String? userId,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserIdAndLatest,
          [
            userId,
            count,
          ],
        ),
        returnValue: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByUserIdAndLatest,
            [
              userId,
              count,
            ],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByUserIdAndLatest,
            [
              userId,
              count,
            ],
          ),
        )),
      ) as _i7.Future<_i3.TUserPostFavoriteList>);

  @override
  _i7.Future<_i3.TUserPostFavoriteList> findByUserIdAndLatestAt(
    String? userId,
    DateTime? latestAt,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserIdAndLatestAt,
          [
            userId,
            latestAt,
            count,
          ],
        ),
        returnValue: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByUserIdAndLatestAt,
            [
              userId,
              latestAt,
              count,
            ],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByUserIdAndLatestAt,
            [
              userId,
              latestAt,
              count,
            ],
          ),
        )),
      ) as _i7.Future<_i3.TUserPostFavoriteList>);

  @override
  _i7.Future<_i3.TUserPostFavoriteList> findByUserIdAndOldestAt(
    String? userId,
    DateTime? oldestAt,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserIdAndOldestAt,
          [
            userId,
            oldestAt,
            count,
          ],
        ),
        returnValue: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByUserIdAndOldestAt,
            [
              userId,
              oldestAt,
              count,
            ],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i3.TUserPostFavoriteList>.value(
            _FakeTUserPostFavoriteList_1(
          this,
          Invocation.method(
            #findByUserIdAndOldestAt,
            [
              userId,
              oldestAt,
              count,
            ],
          ),
        )),
      ) as _i7.Future<_i3.TUserPostFavoriteList>);
}

/// A class which mocks [VPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVPostRepository extends _i1.Mock implements _i8.VPostRepository {
  @override
  _i7.Future<_i4.VPost> findByPostId(int? postId) => (super.noSuchMethod(
        Invocation.method(
          #findByPostId,
          [postId],
        ),
        returnValue: _i7.Future<_i4.VPost>.value(_FakeVPost_2(
          this,
          Invocation.method(
            #findByPostId,
            [postId],
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i4.VPost>.value(_FakeVPost_2(
          this,
          Invocation.method(
            #findByPostId,
            [postId],
          ),
        )),
      ) as _i7.Future<_i4.VPost>);

  @override
  _i7.Future<_i5.VPostList> findByPostIdList(_i9.PostIdList? postIdList) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByPostIdList,
          [postIdList],
        ),
        returnValue: _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByPostIdList,
            [postIdList],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByPostIdList,
            [postIdList],
          ),
        )),
      ) as _i7.Future<_i5.VPostList>);

  @override
  _i7.Future<_i5.VPostList> findByLatest(int? count) => (super.noSuchMethod(
        Invocation.method(
          #findByLatest,
          [count],
        ),
        returnValue: _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByLatest,
            [count],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByLatest,
            [count],
          ),
        )),
      ) as _i7.Future<_i5.VPostList>);

  @override
  _i7.Future<_i5.VPostList> findBySincePostId(
    int? sincePostId,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findBySincePostId,
          [
            sincePostId,
            count,
          ],
        ),
        returnValue: _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findBySincePostId,
            [
              sincePostId,
              count,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findBySincePostId,
            [
              sincePostId,
              count,
            ],
          ),
        )),
      ) as _i7.Future<_i5.VPostList>);

  @override
  _i7.Future<_i5.VPostList> findByMaxPostId(
    int? maxPostId,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByMaxPostId,
          [
            maxPostId,
            count,
          ],
        ),
        returnValue: _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByMaxPostId,
            [
              maxPostId,
              count,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByMaxPostId,
            [
              maxPostId,
              count,
            ],
          ),
        )),
      ) as _i7.Future<_i5.VPostList>);

  @override
  _i7.Future<_i5.VPostList> findByUserIdAndLatest(
    String? userId,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserIdAndLatest,
          [
            userId,
            count,
          ],
        ),
        returnValue: _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByUserIdAndLatest,
            [
              userId,
              count,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByUserIdAndLatest,
            [
              userId,
              count,
            ],
          ),
        )),
      ) as _i7.Future<_i5.VPostList>);

  @override
  _i7.Future<_i5.VPostList> findByUserIdAndSincePostId(
    String? userId,
    int? sincePostId,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserIdAndSincePostId,
          [
            userId,
            sincePostId,
            count,
          ],
        ),
        returnValue: _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByUserIdAndSincePostId,
            [
              userId,
              sincePostId,
              count,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByUserIdAndSincePostId,
            [
              userId,
              sincePostId,
              count,
            ],
          ),
        )),
      ) as _i7.Future<_i5.VPostList>);

  @override
  _i7.Future<_i5.VPostList> findByUserIdAndMaxPostId(
    String? userId,
    int? maxPostId,
    int? count,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserIdAndMaxPostId,
          [
            userId,
            maxPostId,
            count,
          ],
        ),
        returnValue: _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByUserIdAndMaxPostId,
            [
              userId,
              maxPostId,
              count,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i5.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #findByUserIdAndMaxPostId,
            [
              userId,
              maxPostId,
              count,
            ],
          ),
        )),
      ) as _i7.Future<_i5.VPostList>);
}
