// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/application/interactors/find_user_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gynx_app/src/domain/entities/v_user.dart' as _i2;
import 'package:gynx_app/src/domain/repositories/v_user_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVUser_0 extends _i1.SmartFake implements _i2.VUser {
  _FakeVUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVUserRepository extends _i1.Mock implements _i3.VUserRepository {
  @override
  _i4.Future<_i2.VUser> findByUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue: _i4.Future<_i2.VUser>.value(_FakeVUser_0(
          this,
          Invocation.method(
            #findByUserId,
            [userId],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.VUser>.value(_FakeVUser_0(
          this,
          Invocation.method(
            #findByUserId,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.VUser>);

  @override
  _i4.Future<_i2.VUser> findByGynxId(String? gynxId) => (super.noSuchMethod(
        Invocation.method(
          #findByGynxId,
          [gynxId],
        ),
        returnValue: _i4.Future<_i2.VUser>.value(_FakeVUser_0(
          this,
          Invocation.method(
            #findByGynxId,
            [gynxId],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.VUser>.value(_FakeVUser_0(
          this,
          Invocation.method(
            #findByGynxId,
            [gynxId],
          ),
        )),
      ) as _i4.Future<_i2.VUser>);
}
