// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/application/interactors/suite_user_interactor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:gynx_app/src/domain/entities/t_user.dart' as _i2;
import 'package:gynx_app/src/domain/entities/t_user_profile.dart' as _i3;
import 'package:gynx_app/src/domain/repositories/auth_repository.dart' as _i4;
import 'package:gynx_app/src/domain/repositories/t_user_profile_repository.dart'
    as _i7;
import 'package:gynx_app/src/domain/repositories/t_user_repository.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTUser_0 extends _i1.SmartFake implements _i2.TUser {
  _FakeTUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTUserProfile_1 extends _i1.SmartFake implements _i3.TUserProfile {
  _FakeTUserProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  @override
  bool isSignedIn() => (super.noSuchMethod(
        Invocation.method(
          #isSignedIn,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.Future<void> signInWithAnonymous() => (super.noSuchMethod(
        Invocation.method(
          #signInWithAnonymous,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> linkWithApple() => (super.noSuchMethod(
        Invocation.method(
          #linkWithApple,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> linkWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #linkWithGoogle,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> linkWithX() => (super.noSuchMethod(
        Invocation.method(
          #linkWithX,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> linkWithTwitch() => (super.noSuchMethod(
        Invocation.method(
          #linkWithTwitch,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> linkWithDiscord() => (super.noSuchMethod(
        Invocation.method(
          #linkWithDiscord,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTUserRepository extends _i1.Mock implements _i6.TUserRepository {
  @override
  _i5.Future<_i2.TUser> findByPrimaryKey(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findByPrimaryKey,
          [id],
        ),
        returnValue: _i5.Future<_i2.TUser>.value(_FakeTUser_0(
          this,
          Invocation.method(
            #findByPrimaryKey,
            [id],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.TUser>.value(_FakeTUser_0(
          this,
          Invocation.method(
            #findByPrimaryKey,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.TUser>);

  @override
  _i5.Future<_i2.TUser> findByGynxId(String? gynxId) => (super.noSuchMethod(
        Invocation.method(
          #findByGynxId,
          [gynxId],
        ),
        returnValue: _i5.Future<_i2.TUser>.value(_FakeTUser_0(
          this,
          Invocation.method(
            #findByGynxId,
            [gynxId],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.TUser>.value(_FakeTUser_0(
          this,
          Invocation.method(
            #findByGynxId,
            [gynxId],
          ),
        )),
      ) as _i5.Future<_i2.TUser>);

  @override
  _i5.Future<void> updateByPrimaryKey({
    required String? id,
    required String? gynxId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateByPrimaryKey,
          [],
          {
            #id: id,
            #gynxId: gynxId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [TUserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTUserProfileRepository extends _i1.Mock
    implements _i7.TUserProfileRepository {
  @override
  _i5.Future<_i3.TUserProfile> findByPrimaryKey(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByPrimaryKey,
          [userId],
        ),
        returnValue: _i5.Future<_i3.TUserProfile>.value(_FakeTUserProfile_1(
          this,
          Invocation.method(
            #findByPrimaryKey,
            [userId],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.TUserProfile>.value(_FakeTUserProfile_1(
          this,
          Invocation.method(
            #findByPrimaryKey,
            [userId],
          ),
        )),
      ) as _i5.Future<_i3.TUserProfile>);

  @override
  _i5.Future<void> updateByPrimaryKeySelective({
    required String? userId,
    required String? username,
    required String? avatarUrl,
    bool? isDeleteAvatarUrl = false,
    required String? selfIntroduction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateByPrimaryKeySelective,
          [],
          {
            #userId: userId,
            #username: username,
            #avatarUrl: avatarUrl,
            #isDeleteAvatarUrl: isDeleteAvatarUrl,
            #selfIntroduction: selfIntroduction,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
