// Mocks generated by Mockito 5.4.5 from annotations
// in gynx_app/test/src/presentation/pages/profile/profile_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/material.dart' as _i8;
import 'package:gynx_app/src/domain/models/suite_user.dart' as _i2;
import 'package:gynx_app/src/domain/usecases/suite_user_usecase.dart' as _i6;
import 'package:gynx_app/src/presentation/navigation/page_navigator.dart'
    as _i7;
import 'package:gynx_app/src/presentation/navigation/page_type.dart' as _i9;
import 'package:gynx_app/src/presentation/pages/profile/profile_controller.dart'
    as _i3;
import 'package:gynx_l10n/gynx_l10n.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSuiteUser_0 extends _i1.SmartFake implements _i2.SuiteUser {
  _FakeSuiteUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileController].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileController extends _i1.Mock implements _i3.ProfileController {
  @override
  _i4.Future<void> signOut(_i5.L10n? l10n) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [l10n]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SuiteUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuiteUserUseCase extends _i1.Mock implements _i6.SuiteUserUseCase {
  @override
  _i4.Future<_i2.SuiteUser> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<_i2.SuiteUser>.value(
              _FakeSuiteUser_0(this, Invocation.method(#execute, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SuiteUser>.value(
              _FakeSuiteUser_0(this, Invocation.method(#execute, [])),
            ),
          )
          as _i4.Future<_i2.SuiteUser>);
}

/// A class which mocks [PageNavigator].
///
/// See the documentation for Mockito's code generation for more information.
class MockPageNavigator extends _i1.Mock implements _i7.PageNavigator {
  @override
  void pop<T extends Object?>(_i8.BuildContext? context, [T? result]) =>
      super.noSuchMethod(
        Invocation.method(#pop, [context, result]),
        returnValueForMissingStub: null,
      );

  @override
  void push(
    _i8.BuildContext? context,
    _i9.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) => super.noSuchMethod(
    Invocation.method(
      #push,
      [context, pageType],
      {#pathParams: pathParams, #queryParams: queryParams},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void go(
    _i8.BuildContext? context,
    _i9.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) => super.noSuchMethod(
    Invocation.method(
      #go,
      [context, pageType],
      {#pathParams: pathParams, #queryParams: queryParams},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void pushReplacement(
    _i8.BuildContext? context,
    _i9.PageType? pageType, {
    Map<String, dynamic>? pathParams,
    Map<String, dynamic>? queryParams,
  }) => super.noSuchMethod(
    Invocation.method(
      #pushReplacement,
      [context, pageType],
      {#pathParams: pathParams, #queryParams: queryParams},
    ),
    returnValueForMissingStub: null,
  );
}
