// Mocks generated by Mockito 5.4.5 from annotations
// in app/test/src/presentation/pages/profile/profile_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:app/src/domain/usecases/sign_out_usecase.dart' as _i4;
import 'package:app/src/presentation/dialogs/loading_dialog.dart' as _i2;
import 'package:app/src/presentation/dialogs/notify.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoadingDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadingDialog extends _i1.Mock implements _i2.LoadingDialog {
  @override
  void show() => super.noSuchMethod(
        Invocation.method(#show, []),
        returnValueForMissingStub: null,
      );

  @override
  void hide() => super.noSuchMethod(
        Invocation.method(#hide, []),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Notify].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotify extends _i1.Mock implements _i3.Notify {
  @override
  void showError({required String? message}) => super.noSuchMethod(
        Invocation.method(#showError, [], {#message: message}),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SignOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUseCase extends _i1.Mock implements _i4.SignOutUseCase {
  @override
  _i5.Future<void> execute() => (super.noSuchMethod(
        Invocation.method(#execute, []),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
