// Mocks generated by Mockito 5.4.5 from annotations
// in app/test/src/presentation/pages/edit_profile/edit_profile_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/src/domain/models/suite_user.dart' as _i2;
import 'package:app/src/domain/usecases/suite_user_usecase.dart' as _i9;
import 'package:app/src/presentation/pages/edit_profile/edit_profile_controller.dart'
    as _i3;
import 'package:flutter/material.dart' as _i5;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i7;
import 'package:gynx_l10n/gynx_l10n.dart' as _i6;
import 'package:image_picker/image_picker.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSuiteUser_0 extends _i1.SmartFake implements _i2.SuiteUser {
  _FakeSuiteUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EditProfileController].
///
/// See the documentation for Mockito's code generation for more information.
class MockEditProfileController extends _i1.Mock
    implements _i3.EditProfileController {
  @override
  _i4.Future<void> updateUserProfile({
    required _i5.BuildContext? context,
    required _i6.L10n? l10n,
    required _i7.WidgetRef? ref,
    required String? gynxId,
    required String? username,
    required _i8.XFile? avatarFile,
    required bool? isDeleteAvatar,
    required String? selfIntroduction,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #context: context,
              #l10n: l10n,
              #ref: ref,
              #gynxId: gynxId,
              #username: username,
              #avatarFile: avatarFile,
              #isDeleteAvatar: isDeleteAvatar,
              #selfIntroduction: selfIntroduction,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SuiteUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuiteUserUseCase extends _i1.Mock implements _i9.SuiteUserUseCase {
  @override
  _i4.Future<_i2.SuiteUser> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<_i2.SuiteUser>.value(
              _FakeSuiteUser_0(this, Invocation.method(#execute, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.SuiteUser>.value(
              _FakeSuiteUser_0(this, Invocation.method(#execute, [])),
            ),
          )
          as _i4.Future<_i2.SuiteUser>);
}
