name: gynx_app
version: 0.0.0
publish_to: none
environment:
  sdk: ^3.6.0
  flutter: ^3.29.1
dev_dependencies:
  build_runner: 2.4.15
  envied_generator: 1.1.1
  flutter_gen_runner: 5.10.0
  flutter_launcher_icons: 0.14.3
  freezed: 3.0.3
  go_router_builder: 2.8.2
  injectable_generator: 2.7.0
  json_serializable: 6.9.4
  mockito: 5.4.5
  riverpod_generator: 2.6.5
resolution: workspace
flutter_gen:
  output: lib/src/generated/assets
  integrations:
    flutter_svg: true
flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/svgs/logos/
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: assets/images/app_icon.png
  image_path_ios_dark_transparent: assets/images/app_icon.png
  image_path_android: assets/images/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/app_icon_android.png
flutter_native_splash:
  color: "#1A1221"
  image: assets/images/splash_logo.png
  branding: assets/images/branding.png
  branding_mode: bottom
  branding_bottom_padding: 48
  color_dark: "#1A1221"
  image_dark: assets/images/splash_logo.png
  branding_dark: assets/images/branding.png
  android_12:
    icon_background_color: "#1A1221"
    image: assets/images/splash_logo_android12.png
    icon_background_color_dark: "#1A1221"
    image_dark: assets/images/splash_logo_android12.png
