// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_core/test/src/interface/pages/sign_in/sign_in_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i8;

import 'package:flutter_clean_architecture/flutter_clean_architecture.dart'
    as _i6;
import 'package:gynx_core/src/application/usecase/interactors/sign_in_interactor.dart'
    as _i3;
import 'package:gynx_core/src/application/usecase/params/sign_in_param.dart'
    as _i5;
import 'package:gynx_core/src/interface/pages/sign_in/sign_in_presenter.dart'
    as _i7;
import 'package:logging/logging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInInteractor extends _i1.Mock implements _i3.SignInInteractor {
  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i4.Future<_i4.Stream<void>> buildUseCaseStream(_i5.SignInParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUseCaseStream,
          [params],
        ),
        returnValue:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
        returnValueForMissingStub:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
      ) as _i4.Future<_i4.Stream<void>>);

  @override
  void execute(
    _i6.Observer<void>? observer, [
    _i5.SignInParam? params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            observer,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SignInPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInPresenter extends _i1.Mock implements _i7.SignInPresenter {
  @override
  _i8.VoidCallback get signInOnComplete => (super.noSuchMethod(
        Invocation.getter(#signInOnComplete),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i8.VoidCallback);

  @override
  set signInOnComplete(_i8.VoidCallback? _signInOnComplete) =>
      super.noSuchMethod(
        Invocation.setter(
          #signInOnComplete,
          _signInOnComplete,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void Function(dynamic) get signInOnError => (super.noSuchMethod(
        Invocation.getter(#signInOnError),
        returnValue: (dynamic __p0) {},
        returnValueForMissingStub: (dynamic __p0) {},
      ) as void Function(dynamic));

  @override
  set signInOnError(void Function(dynamic)? _signInOnError) =>
      super.noSuchMethod(
        Invocation.setter(
          #signInOnError,
          _signInOnError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void signIn(
    String? email,
    String? password,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
