// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/interface/pages/sign_in/sign_in_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i3;
import 'package:flutter/services.dart' as _i9;
import 'package:gynx_app/src/interface/pages/sign_in/sign_in_controller.dart'
    as _i5;
import 'package:gynx_app/src/interface/router/page_router.dart' as _i11;
import 'package:gynx_app/src/interface/router/page_type.dart' as _i12;
import 'package:gynx_l10n/gynx_l10n.dart' as _i7;
import 'package:logging/logging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:supabase/supabase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeState_1<T extends _i3.StatefulWidget> extends _i1.SmartFake
    implements _i3.State<T> {
  _FakeState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeGlobalKey_2<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake implements _i3.GlobalKey<T> {
  _FakeGlobalKey_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBuildContext_3 extends _i1.SmartFake implements _i3.BuildContext {
  _FakeBuildContext_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionsClient_4 extends _i1.SmartFake
    implements _i4.FunctionsClient {
  _FakeFunctionsClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseStorageClient_5 extends _i1.SmartFake
    implements _i4.SupabaseStorageClient {
  _FakeSupabaseStorageClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeClient_6 extends _i1.SmartFake
    implements _i4.RealtimeClient {
  _FakeRealtimeClient_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestClient_7 extends _i1.SmartFake
    implements _i4.PostgrestClient {
  _FakePostgrestClient_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueClient_8 extends _i1.SmartFake implements _i4.GoTrueClient {
  _FakeGoTrueClient_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQueryBuilder_9 extends _i1.SmartFake
    implements _i4.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupabaseQuerySchema_10 extends _i1.SmartFake
    implements _i4.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostgrestFilterBuilder_11<T1> extends _i1.SmartFake
    implements _i4.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealtimeChannel_12 extends _i1.SmartFake
    implements _i4.RealtimeChannel {
  _FakeRealtimeChannel_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueAdminApi_13 extends _i1.SmartFake
    implements _i4.GoTrueAdminApi {
  _FakeGoTrueAdminApi_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoTrueMFAApi_14 extends _i1.SmartFake implements _i4.GoTrueMFAApi {
  _FakeGoTrueMFAApi_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResponse_15 extends _i1.SmartFake implements _i4.AuthResponse {
  _FakeAuthResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOAuthResponse_16 extends _i1.SmartFake implements _i4.OAuthResponse {
  _FakeOAuthResponse_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthSessionUrlResponse_17 extends _i1.SmartFake
    implements _i4.AuthSessionUrlResponse {
  _FakeAuthSessionUrlResponse_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResendResponse_18 extends _i1.SmartFake
    implements _i4.ResendResponse {
  _FakeResendResponse_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserResponse_19 extends _i1.SmartFake implements _i4.UserResponse {
  _FakeUserResponse_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_20 extends _i1.SmartFake implements Object {
  _FakeObject_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_21 extends _i1.SmartFake implements _i4.User {
  _FakeUser_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSession_22 extends _i1.SmartFake implements _i4.Session {
  _FakeSession_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInController extends _i1.Mock implements _i5.SignInController {
  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  set logger(_i2.Logger? _logger) => super.noSuchMethod(
        Invocation.setter(
          #logger,
          _logger,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void signInWithApple() => super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void signInWithGoogle() => super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> signInWithAnonymous(_i7.L10n? l10n) => (super.noSuchMethod(
        Invocation.method(
          #signInWithAnonymous,
          [l10n],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void initListeners() => super.noSuchMethod(
        Invocation.method(
          #initListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAppLifecycleState(_i8.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeAppLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshUI() => super.noSuchMethod(
        Invocation.method(
          #refreshUI,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDisposed() => super.noSuchMethod(
        Invocation.method(
          #onDisposed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.State<_i3.StatefulWidget> getState() => (super.noSuchMethod(
        Invocation.method(
          #getState,
          [],
        ),
        returnValue: _FakeState_1<_i3.StatefulWidget>(
          this,
          Invocation.method(
            #getState,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeState_1<_i3.StatefulWidget>(
          this,
          Invocation.method(
            #getState,
            [],
          ),
        ),
      ) as _i3.State<_i3.StatefulWidget>);

  @override
  _i3.GlobalKey<_i3.State<_i3.StatefulWidget>> getStateKey() =>
      (super.noSuchMethod(
        Invocation.method(
          #getStateKey,
          [],
        ),
        returnValue: _FakeGlobalKey_2<_i3.State<_i3.StatefulWidget>>(
          this,
          Invocation.method(
            #getStateKey,
            [],
          ),
        ),
        returnValueForMissingStub:
            _FakeGlobalKey_2<_i3.State<_i3.StatefulWidget>>(
          this,
          Invocation.method(
            #getStateKey,
            [],
          ),
        ),
      ) as _i3.GlobalKey<_i3.State<_i3.StatefulWidget>>);

  @override
  void initController(_i3.GlobalKey<_i3.State<_i3.StatefulWidget>>? key) =>
      super.noSuchMethod(
        Invocation.method(
          #initController,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.BuildContext getContext() => (super.noSuchMethod(
        Invocation.method(
          #getContext,
          [],
        ),
        returnValue: _FakeBuildContext_3(
          this,
          Invocation.method(
            #getContext,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeBuildContext_3(
          this,
          Invocation.method(
            #getContext,
            [],
          ),
        ),
      ) as _i3.BuildContext);

  @override
  void onInActive() => super.noSuchMethod(
        Invocation.method(
          #onInActive,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPaused() => super.noSuchMethod(
        Invocation.method(
          #onPaused,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onResumed() => super.noSuchMethod(
        Invocation.method(
          #onResumed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDetached() => super.noSuchMethod(
        Invocation.method(
          #onDetached,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onHidden() => super.noSuchMethod(
        Invocation.method(
          #onHidden,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDeactivated() => super.noSuchMethod(
        Invocation.method(
          #onDeactivated,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReassembled() => super.noSuchMethod(
        Invocation.method(
          #onReassembled,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDidChangeDependencies() => super.noSuchMethod(
        Invocation.method(
          #onDidChangeDependencies,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInitState() => super.noSuchMethod(
        Invocation.method(
          #onInitState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> didPopRoute() => (super.noSuchMethod(
        Invocation.method(
          #didPopRoute,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  bool handleStartBackGesture(_i9.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleStartBackGesture,
          [backEvent],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void handleUpdateBackGestureProgress(_i9.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(
          #handleUpdateBackGestureProgress,
          [backEvent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCommitBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCancelBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #didPushRoute,
          [route],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> didPushRouteInformation(
          _i3.RouteInformation? routeInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #didPushRouteInformation,
          [routeInformation],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
        Invocation.method(
          #didChangeMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
        Invocation.method(
          #didChangeTextScaleFactor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
        Invocation.method(
          #didChangePlatformBrightness,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeLocales(List<_i8.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #didChangeLocales,
          [locales],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i8.ViewFocusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #didChangeViewFocus,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i8.AppExitResponse> didRequestAppExit() => (super.noSuchMethod(
        Invocation.method(
          #didRequestAppExit,
          [],
        ),
        returnValue:
            _i6.Future<_i8.AppExitResponse>.value(_i8.AppExitResponse.exit),
        returnValueForMissingStub:
            _i6.Future<_i8.AppExitResponse>.value(_i8.AppExitResponse.exit),
      ) as _i6.Future<_i8.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #didHaveMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
        Invocation.method(
          #didChangeAccessibilityFeatures,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPopNext() => super.noSuchMethod(
        Invocation.method(
          #didPopNext,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPush() => super.noSuchMethod(
        Invocation.method(
          #didPush,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPop() => super.noSuchMethod(
        Invocation.method(
          #didPop,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didPushNext() => super.noSuchMethod(
        Invocation.method(
          #didPushNext,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i4.SupabaseClient {
  @override
  _i4.FunctionsClient get functions => (super.noSuchMethod(
        Invocation.getter(#functions),
        returnValue: _FakeFunctionsClient_4(
          this,
          Invocation.getter(#functions),
        ),
        returnValueForMissingStub: _FakeFunctionsClient_4(
          this,
          Invocation.getter(#functions),
        ),
      ) as _i4.FunctionsClient);

  @override
  set functions(_i4.FunctionsClient? _functions) => super.noSuchMethod(
        Invocation.setter(
          #functions,
          _functions,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.SupabaseStorageClient get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeSupabaseStorageClient_5(
          this,
          Invocation.getter(#storage),
        ),
        returnValueForMissingStub: _FakeSupabaseStorageClient_5(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i4.SupabaseStorageClient);

  @override
  set storage(_i4.SupabaseStorageClient? _storage) => super.noSuchMethod(
        Invocation.setter(
          #storage,
          _storage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RealtimeClient get realtime => (super.noSuchMethod(
        Invocation.getter(#realtime),
        returnValue: _FakeRealtimeClient_6(
          this,
          Invocation.getter(#realtime),
        ),
        returnValueForMissingStub: _FakeRealtimeClient_6(
          this,
          Invocation.getter(#realtime),
        ),
      ) as _i4.RealtimeClient);

  @override
  set realtime(_i4.RealtimeClient? _realtime) => super.noSuchMethod(
        Invocation.setter(
          #realtime,
          _realtime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.PostgrestClient get rest => (super.noSuchMethod(
        Invocation.getter(#rest),
        returnValue: _FakePostgrestClient_7(
          this,
          Invocation.getter(#rest),
        ),
        returnValueForMissingStub: _FakePostgrestClient_7(
          this,
          Invocation.getter(#rest),
        ),
      ) as _i4.PostgrestClient);

  @override
  set rest(_i4.PostgrestClient? _rest) => super.noSuchMethod(
        Invocation.setter(
          #rest,
          _rest,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          headers,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.GoTrueClient get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeGoTrueClient_8(
          this,
          Invocation.getter(#auth),
        ),
        returnValueForMissingStub: _FakeGoTrueClient_8(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i4.GoTrueClient);

  @override
  _i4.SupabaseQueryBuilder from(String? table) => (super.noSuchMethod(
        Invocation.method(
          #from,
          [table],
        ),
        returnValue: _FakeSupabaseQueryBuilder_9(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
        returnValueForMissingStub: _FakeSupabaseQueryBuilder_9(
          this,
          Invocation.method(
            #from,
            [table],
          ),
        ),
      ) as _i4.SupabaseQueryBuilder);

  @override
  _i4.SupabaseQuerySchema schema(String? schema) => (super.noSuchMethod(
        Invocation.method(
          #schema,
          [schema],
        ),
        returnValue: _FakeSupabaseQuerySchema_10(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
        returnValueForMissingStub: _FakeSupabaseQuerySchema_10(
          this,
          Invocation.method(
            #schema,
            [schema],
          ),
        ),
      ) as _i4.SupabaseQuerySchema);

  @override
  _i4.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [fn],
          {
            #params: params,
            #get: get,
          },
        ),
        returnValue: _FakePostgrestFilterBuilder_11<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
        returnValueForMissingStub: _FakePostgrestFilterBuilder_11<T>(
          this,
          Invocation.method(
            #rpc,
            [fn],
            {
              #params: params,
              #get: get,
            },
          ),
        ),
      ) as _i4.PostgrestFilterBuilder<T>);

  @override
  _i4.RealtimeChannel channel(
    String? name, {
    _i4.RealtimeChannelConfig? opts = const _i4.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #channel,
          [name],
          {#opts: opts},
        ),
        returnValue: _FakeRealtimeChannel_12(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
        returnValueForMissingStub: _FakeRealtimeChannel_12(
          this,
          Invocation.method(
            #channel,
            [name],
            {#opts: opts},
          ),
        ),
      ) as _i4.RealtimeChannel);

  @override
  List<_i4.RealtimeChannel> getChannels() => (super.noSuchMethod(
        Invocation.method(
          #getChannels,
          [],
        ),
        returnValue: <_i4.RealtimeChannel>[],
        returnValueForMissingStub: <_i4.RealtimeChannel>[],
      ) as List<_i4.RealtimeChannel>);

  @override
  _i6.Future<String> removeChannel(_i4.RealtimeChannel? channel) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeChannel,
          [channel],
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #removeChannel,
            [channel],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<List<String>> removeAllChannels() => (super.noSuchMethod(
        Invocation.method(
          #removeAllChannels,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [GoTrueClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoTrueClient extends _i1.Mock implements _i4.GoTrueClient {
  @override
  _i4.GoTrueAdminApi get admin => (super.noSuchMethod(
        Invocation.getter(#admin),
        returnValue: _FakeGoTrueAdminApi_13(
          this,
          Invocation.getter(#admin),
        ),
        returnValueForMissingStub: _FakeGoTrueAdminApi_13(
          this,
          Invocation.getter(#admin),
        ),
      ) as _i4.GoTrueAdminApi);

  @override
  set admin(_i4.GoTrueAdminApi? _admin) => super.noSuchMethod(
        Invocation.setter(
          #admin,
          _admin,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.GoTrueMFAApi get mfa => (super.noSuchMethod(
        Invocation.getter(#mfa),
        returnValue: _FakeGoTrueMFAApi_14(
          this,
          Invocation.getter(#mfa),
        ),
        returnValueForMissingStub: _FakeGoTrueMFAApi_14(
          this,
          Invocation.getter(#mfa),
        ),
      ) as _i4.GoTrueMFAApi);

  @override
  set mfa(_i4.GoTrueMFAApi? _mfa) => super.noSuchMethod(
        Invocation.setter(
          #mfa,
          _mfa,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<_i4.AuthState> get onAuthStateChange => (super.noSuchMethod(
        Invocation.getter(#onAuthStateChange),
        returnValue: _i6.Stream<_i4.AuthState>.empty(),
        returnValueForMissingStub: _i6.Stream<_i4.AuthState>.empty(),
      ) as _i6.Stream<_i4.AuthState>);

  @override
  _i6.Stream<_i4.AuthState> get onAuthStateChangeSync => (super.noSuchMethod(
        Invocation.getter(#onAuthStateChangeSync),
        returnValue: _i6.Stream<_i4.AuthState>.empty(),
        returnValueForMissingStub: _i6.Stream<_i4.AuthState>.empty(),
      ) as _i6.Stream<_i4.AuthState>);

  @override
  Map<String, String> get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: <String, String>{},
        returnValueForMissingStub: <String, String>{},
      ) as Map<String, String>);

  @override
  _i6.Future<_i4.AuthResponse> signInAnonymously({
    Map<String, dynamic>? data,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
          {
            #data: data,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
            {
              #data: data,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
            {
              #data: data,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.AuthResponse> signUp({
    String? email,
    String? phone,
    required String? password,
    String? emailRedirectTo,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i4.OtpChannel? channel = _i4.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #emailRedirectTo: emailRedirectTo,
            #data: data,
            #captchaToken: captchaToken,
            #channel: channel,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #signUp,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #emailRedirectTo: emailRedirectTo,
              #data: data,
              #captchaToken: captchaToken,
              #channel: channel,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.AuthResponse> signInWithPassword({
    String? email,
    String? phone,
    required String? password,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithPassword,
          [],
          {
            #email: email,
            #phone: phone,
            #password: password,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #signInWithPassword,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #signInWithPassword,
            [],
            {
              #email: email,
              #phone: phone,
              #password: password,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.OAuthResponse> getOAuthSignInUrl({
    required _i4.OAuthProvider? provider,
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOAuthSignInUrl,
          [],
          {
            #provider: provider,
            #redirectTo: redirectTo,
            #scopes: scopes,
            #queryParams: queryParams,
          },
        ),
        returnValue: _i6.Future<_i4.OAuthResponse>.value(_FakeOAuthResponse_16(
          this,
          Invocation.method(
            #getOAuthSignInUrl,
            [],
            {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.OAuthResponse>.value(_FakeOAuthResponse_16(
          this,
          Invocation.method(
            #getOAuthSignInUrl,
            [],
            {
              #provider: provider,
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
      ) as _i6.Future<_i4.OAuthResponse>);

  @override
  _i6.Future<_i4.AuthSessionUrlResponse> exchangeCodeForSession(
          String? authCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #exchangeCodeForSession,
          [authCode],
        ),
        returnValue: _i6.Future<_i4.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_17(
          this,
          Invocation.method(
            #exchangeCodeForSession,
            [authCode],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i4.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_17(
          this,
          Invocation.method(
            #exchangeCodeForSession,
            [authCode],
          ),
        )),
      ) as _i6.Future<_i4.AuthSessionUrlResponse>);

  @override
  _i6.Future<_i4.AuthResponse> signInWithIdToken({
    required _i4.OAuthProvider? provider,
    required String? idToken,
    String? accessToken,
    String? nonce,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithIdToken,
          [],
          {
            #provider: provider,
            #idToken: idToken,
            #accessToken: accessToken,
            #nonce: nonce,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #signInWithIdToken,
            [],
            {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #signInWithIdToken,
            [],
            {
              #provider: provider,
              #idToken: idToken,
              #accessToken: accessToken,
              #nonce: nonce,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<void> signInWithOtp({
    String? email,
    String? phone,
    String? emailRedirectTo,
    bool? shouldCreateUser,
    Map<String, dynamic>? data,
    String? captchaToken,
    _i4.OtpChannel? channel = _i4.OtpChannel.sms,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithOtp,
          [],
          {
            #email: email,
            #phone: phone,
            #emailRedirectTo: emailRedirectTo,
            #shouldCreateUser: shouldCreateUser,
            #data: data,
            #captchaToken: captchaToken,
            #channel: channel,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.AuthResponse> verifyOTP({
    String? email,
    String? phone,
    String? token,
    required _i4.OtpType? type,
    String? redirectTo,
    String? captchaToken,
    String? tokenHash,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOTP,
          [],
          {
            #email: email,
            #phone: phone,
            #token: token,
            #type: type,
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
            #tokenHash: tokenHash,
          },
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #verifyOTP,
            [],
            {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #verifyOTP,
            [],
            {
              #email: email,
              #phone: phone,
              #token: token,
              #type: type,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
              #tokenHash: tokenHash,
            },
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<String> getSSOSignInUrl({
    String? providerId,
    String? domain,
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSSOSignInUrl,
          [],
          {
            #providerId: providerId,
            #domain: domain,
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getSSOSignInUrl,
            [],
            {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getSSOSignInUrl,
            [],
            {
              #providerId: providerId,
              #domain: domain,
              #redirectTo: redirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i4.AuthResponse> refreshSession([String? refreshToken]) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshSession,
          [refreshToken],
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #refreshSession,
            [refreshToken],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #refreshSession,
            [refreshToken],
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<void> reauthenticate() => (super.noSuchMethod(
        Invocation.method(
          #reauthenticate,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.ResendResponse> resend({
    String? email,
    String? phone,
    required _i4.OtpType? type,
    String? emailRedirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resend,
          [],
          {
            #email: email,
            #phone: phone,
            #type: type,
            #emailRedirectTo: emailRedirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue:
            _i6.Future<_i4.ResendResponse>.value(_FakeResendResponse_18(
          this,
          Invocation.method(
            #resend,
            [],
            {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.ResendResponse>.value(_FakeResendResponse_18(
          this,
          Invocation.method(
            #resend,
            [],
            {
              #email: email,
              #phone: phone,
              #type: type,
              #emailRedirectTo: emailRedirectTo,
              #captchaToken: captchaToken,
            },
          ),
        )),
      ) as _i6.Future<_i4.ResendResponse>);

  @override
  _i6.Future<_i4.UserResponse> getUser([String? jwt]) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [jwt],
        ),
        returnValue: _i6.Future<_i4.UserResponse>.value(_FakeUserResponse_19(
          this,
          Invocation.method(
            #getUser,
            [jwt],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.UserResponse>.value(_FakeUserResponse_19(
          this,
          Invocation.method(
            #getUser,
            [jwt],
          ),
        )),
      ) as _i6.Future<_i4.UserResponse>);

  @override
  _i6.Future<_i4.UserResponse> updateUser(
    _i4.UserAttributes? attributes, {
    String? emailRedirectTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [attributes],
          {#emailRedirectTo: emailRedirectTo},
        ),
        returnValue: _i6.Future<_i4.UserResponse>.value(_FakeUserResponse_19(
          this,
          Invocation.method(
            #updateUser,
            [attributes],
            {#emailRedirectTo: emailRedirectTo},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.UserResponse>.value(_FakeUserResponse_19(
          this,
          Invocation.method(
            #updateUser,
            [attributes],
            {#emailRedirectTo: emailRedirectTo},
          ),
        )),
      ) as _i6.Future<_i4.UserResponse>);

  @override
  _i6.Future<_i4.AuthResponse> setSession(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSession,
          [refreshToken],
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #setSession,
            [refreshToken],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #setSession,
            [refreshToken],
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  _i6.Future<_i4.AuthSessionUrlResponse> getSessionFromUrl(
    Uri? originUrl, {
    bool? storeSession = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionFromUrl,
          [originUrl],
          {#storeSession: storeSession},
        ),
        returnValue: _i6.Future<_i4.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_17(
          this,
          Invocation.method(
            #getSessionFromUrl,
            [originUrl],
            {#storeSession: storeSession},
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i4.AuthSessionUrlResponse>.value(
            _FakeAuthSessionUrlResponse_17(
          this,
          Invocation.method(
            #getSessionFromUrl,
            [originUrl],
            {#storeSession: storeSession},
          ),
        )),
      ) as _i6.Future<_i4.AuthSessionUrlResponse>);

  @override
  _i6.Future<void> signOut(
          {_i4.SignOutScope? scope = _i4.SignOutScope.local}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
          {#scope: scope},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetPasswordForEmail(
    String? email, {
    String? redirectTo,
    String? captchaToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPasswordForEmail,
          [email],
          {
            #redirectTo: redirectTo,
            #captchaToken: captchaToken,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.UserIdentity>> getUserIdentities() => (super.noSuchMethod(
        Invocation.method(
          #getUserIdentities,
          [],
        ),
        returnValue:
            _i6.Future<List<_i4.UserIdentity>>.value(<_i4.UserIdentity>[]),
        returnValueForMissingStub:
            _i6.Future<List<_i4.UserIdentity>>.value(<_i4.UserIdentity>[]),
      ) as _i6.Future<List<_i4.UserIdentity>>);

  @override
  _i6.Future<_i4.OAuthResponse> getLinkIdentityUrl(
    _i4.OAuthProvider? provider, {
    String? redirectTo,
    String? scopes,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLinkIdentityUrl,
          [provider],
          {
            #redirectTo: redirectTo,
            #scopes: scopes,
            #queryParams: queryParams,
          },
        ),
        returnValue: _i6.Future<_i4.OAuthResponse>.value(_FakeOAuthResponse_16(
          this,
          Invocation.method(
            #getLinkIdentityUrl,
            [provider],
            {
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.OAuthResponse>.value(_FakeOAuthResponse_16(
          this,
          Invocation.method(
            #getLinkIdentityUrl,
            [provider],
            {
              #redirectTo: redirectTo,
              #scopes: scopes,
              #queryParams: queryParams,
            },
          ),
        )),
      ) as _i6.Future<_i4.OAuthResponse>);

  @override
  _i6.Future<void> unlinkIdentity(_i4.UserIdentity? identity) =>
      (super.noSuchMethod(
        Invocation.method(
          #unlinkIdentity,
          [identity],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setInitialSession(String? jsonStr) => (super.noSuchMethod(
        Invocation.method(
          #setInitialSession,
          [jsonStr],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.AuthResponse> recoverSession(String? jsonStr) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverSession,
          [jsonStr],
        ),
        returnValue: _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #recoverSession,
            [jsonStr],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AuthResponse>.value(_FakeAuthResponse_15(
          this,
          Invocation.method(
            #recoverSession,
            [jsonStr],
          ),
        )),
      ) as _i6.Future<_i4.AuthResponse>);

  @override
  void startAutoRefresh() => super.noSuchMethod(
        Invocation.method(
          #startAutoRefresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopAutoRefresh() => super.noSuchMethod(
        Invocation.method(
          #stopAutoRefresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyAllSubscribers(
    _i4.AuthChangeEvent? event, {
    _i4.Session? session,
    bool? broadcast = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #notifyAllSubscribers,
          [event],
          {
            #session: session,
            #broadcast: broadcast,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  Object notifyException(
    Object? exception, [
    StackTrace? stackTrace,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #notifyException,
          [
            exception,
            stackTrace,
          ],
        ),
        returnValue: _FakeObject_20(
          this,
          Invocation.method(
            #notifyException,
            [
              exception,
              stackTrace,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeObject_20(
          this,
          Invocation.method(
            #notifyException,
            [
              exception,
              stackTrace,
            ],
          ),
        ),
      ) as Object);
}

/// A class which mocks [AuthState].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthState extends _i1.Mock implements _i4.AuthState {
  @override
  _i4.AuthChangeEvent get event => (super.noSuchMethod(
        Invocation.getter(#event),
        returnValue: _i4.AuthChangeEvent.initialSession,
        returnValueForMissingStub: _i4.AuthChangeEvent.initialSession,
      ) as _i4.AuthChangeEvent);

  @override
  bool get fromBroadcast => (super.noSuchMethod(
        Invocation.getter(#fromBroadcast),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [Session].
///
/// See the documentation for Mockito's code generation for more information.
class MockSession extends _i1.Mock implements _i4.Session {
  @override
  String get accessToken => (super.noSuchMethod(
        Invocation.getter(#accessToken),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#accessToken),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#accessToken),
        ),
      ) as String);

  @override
  String get tokenType => (super.noSuchMethod(
        Invocation.getter(#tokenType),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#tokenType),
        ),
        returnValueForMissingStub: _i10.dummyValue<String>(
          this,
          Invocation.getter(#tokenType),
        ),
      ) as String);

  @override
  _i4.User get user => (super.noSuchMethod(
        Invocation.getter(#user),
        returnValue: _FakeUser_21(
          this,
          Invocation.getter(#user),
        ),
        returnValueForMissingStub: _FakeUser_21(
          this,
          Invocation.getter(#user),
        ),
      ) as _i4.User);

  @override
  set expiresAt(int? _expiresAt) => super.noSuchMethod(
        Invocation.setter(
          #expiresAt,
          _expiresAt,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isExpired => (super.noSuchMethod(
        Invocation.getter(#isExpired),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Session copyWith({
    String? accessToken,
    int? expiresIn,
    String? refreshToken,
    String? tokenType,
    String? providerToken,
    String? providerRefreshToken,
    _i4.User? user,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copyWith,
          [],
          {
            #accessToken: accessToken,
            #expiresIn: expiresIn,
            #refreshToken: refreshToken,
            #tokenType: tokenType,
            #providerToken: providerToken,
            #providerRefreshToken: providerRefreshToken,
            #user: user,
          },
        ),
        returnValue: _FakeSession_22(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #accessToken: accessToken,
              #expiresIn: expiresIn,
              #refreshToken: refreshToken,
              #tokenType: tokenType,
              #providerToken: providerToken,
              #providerRefreshToken: providerRefreshToken,
              #user: user,
            },
          ),
        ),
        returnValueForMissingStub: _FakeSession_22(
          this,
          Invocation.method(
            #copyWith,
            [],
            {
              #accessToken: accessToken,
              #expiresIn: expiresIn,
              #refreshToken: refreshToken,
              #tokenType: tokenType,
              #providerToken: providerToken,
              #providerRefreshToken: providerRefreshToken,
              #user: user,
            },
          ),
        ),
      ) as _i4.Session);
}

/// A class which mocks [PageRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPageRouter extends _i1.Mock implements _i11.PageRouter {
  @override
  void pop(_i3.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #pop,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void push(
    _i3.BuildContext? context,
    _i12.PageType? pageType,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #push,
          [
            context,
            pageType,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void go(
    _i3.BuildContext? context,
    _i12.PageType? pageType,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #go,
          [
            context,
            pageType,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pushReplacement(
    _i3.BuildContext? context,
    _i12.PageType? pageType,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #pushReplacement,
          [
            context,
            pageType,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
