// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/interface/pages/sign_in/sign_in_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i9;

import 'package:flutter/material.dart' as _i10;
import 'package:flutter_clean_architecture/flutter_clean_architecture.dart'
    as _i5;
import 'package:gynx_app/src/application/usecase/interactors/sign_in_with_anonymous_interactor.dart'
    as _i3;
import 'package:gynx_app/src/application/usecase/interactors/sign_in_with_oauth_interactor.dart'
    as _i6;
import 'package:gynx_app/src/application/usecase/params/sign_in_with_oauth_param.dart'
    as _i7;
import 'package:gynx_app/src/domain/enums/oauth_provider_type.dart' as _i11;
import 'package:gynx_app/src/interface/dialogs/alert.dart' as _i14;
import 'package:gynx_app/src/interface/dialogs/loading_dialog.dart' as _i12;
import 'package:gynx_app/src/interface/dialogs/notify.dart' as _i13;
import 'package:gynx_app/src/interface/pages/sign_in/sign_in_presenter.dart'
    as _i8;
import 'package:logging/logging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInWithAnonymousInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithAnonymousInteractor extends _i1.Mock
    implements _i3.SignInWithAnonymousInteractor {
  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i4.Future<_i4.Stream<void>> buildUseCaseStream(dynamic params) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUseCaseStream,
          [params],
        ),
        returnValue:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
        returnValueForMissingStub:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
      ) as _i4.Future<_i4.Stream<void>>);

  @override
  void execute(
    _i5.Observer<void>? observer, [
    dynamic params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            observer,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SignInWithOAuthInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithOAuthInteractor extends _i1.Mock
    implements _i6.SignInWithOAuthInteractor {
  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i4.Future<_i4.Stream<void>> buildUseCaseStream(
          _i7.SignInWithOAuthParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUseCaseStream,
          [params],
        ),
        returnValue:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
        returnValueForMissingStub:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
      ) as _i4.Future<_i4.Stream<void>>);

  @override
  void execute(
    _i5.Observer<void>? observer, [
    _i7.SignInWithOAuthParam? params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            observer,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SignInPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInPresenter extends _i1.Mock implements _i8.SignInPresenter {
  @override
  _i9.VoidCallback get signInOnComplete => (super.noSuchMethod(
        Invocation.getter(#signInOnComplete),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i9.VoidCallback);

  @override
  set signInOnComplete(_i9.VoidCallback? _signInOnComplete) =>
      super.noSuchMethod(
        Invocation.setter(
          #signInOnComplete,
          _signInOnComplete,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.ValueSetter<dynamic> get signInOnError => (super.noSuchMethod(
        Invocation.getter(#signInOnError),
        returnValue: (dynamic value) {},
        returnValueForMissingStub: (dynamic value) {},
      ) as _i10.ValueSetter<dynamic>);

  @override
  set signInOnError(_i10.ValueSetter<dynamic>? _signInOnError) =>
      super.noSuchMethod(
        Invocation.setter(
          #signInOnError,
          _signInOnError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void signInWithAnonymous() => super.noSuchMethod(
        Invocation.method(
          #signInWithAnonymous,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void signInWithOAuth(_i11.OAuthProviderType? oauthProviderType) =>
      super.noSuchMethod(
        Invocation.method(
          #signInWithOAuth,
          [oauthProviderType],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LoadingDialog].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadingDialog extends _i1.Mock implements _i12.LoadingDialog {
  @override
  void show() => super.noSuchMethod(
        Invocation.method(
          #show,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void hide() => super.noSuchMethod(
        Invocation.method(
          #hide,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Notify].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotify extends _i1.Mock implements _i13.Notify {
  @override
  void showError({required String? message}) => super.noSuchMethod(
        Invocation.method(
          #showError,
          [],
          {#message: message},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Alert].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlert extends _i1.Mock implements _i14.Alert {
  @override
  _i4.Future<void> showInfo({
    required String? title,
    required String? text,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showInfo,
          [],
          {
            #title: title,
            #text: text,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i14.AlertResultType> showAlert({
    required String? title,
    required String? text,
    required String? leftButtonText,
    required String? rightButtonText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAlert,
          [],
          {
            #title: title,
            #text: text,
            #leftButtonText: leftButtonText,
            #rightButtonText: rightButtonText,
          },
        ),
        returnValue:
            _i4.Future<_i14.AlertResultType>.value(_i14.AlertResultType.left),
        returnValueForMissingStub:
            _i4.Future<_i14.AlertResultType>.value(_i14.AlertResultType.left),
      ) as _i4.Future<_i14.AlertResultType>);
}
