// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/interface/pages/sign_in/sign_in_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i9;

import 'package:flutter/material.dart' as _i10;
import 'package:flutter_clean_architecture/flutter_clean_architecture.dart'
    as _i5;
import 'package:gynx_app/src/application/usecase/interactors/sign_in_with_anonymous_interactor.dart'
    as _i3;
import 'package:gynx_app/src/application/usecase/interactors/sign_in_with_oauth_interactor.dart'
    as _i6;
import 'package:gynx_app/src/application/usecase/params/sign_in_with_oauth_param.dart'
    as _i7;
import 'package:gynx_app/src/domain/enums/oauth_provider_type.dart' as _i11;
import 'package:gynx_app/src/interface/pages/sign_in/sign_in_presenter.dart'
    as _i8;
import 'package:logging/logging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInWithAnonymousInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithAnonymousInteractor extends _i1.Mock
    implements _i3.SignInWithAnonymousInteractor {
  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i4.Future<_i4.Stream<void>> buildUseCaseStream(dynamic params) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUseCaseStream,
          [params],
        ),
        returnValue:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
        returnValueForMissingStub:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
      ) as _i4.Future<_i4.Stream<void>>);

  @override
  void execute(
    _i5.Observer<void>? observer, [
    dynamic params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            observer,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SignInWithOAuthInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithOAuthInteractor extends _i1.Mock
    implements _i6.SignInWithOAuthInteractor {
  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i4.Future<_i4.Stream<void>> buildUseCaseStream(
          _i7.SignInWithOAuthParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUseCaseStream,
          [params],
        ),
        returnValue:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
        returnValueForMissingStub:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
      ) as _i4.Future<_i4.Stream<void>>);

  @override
  void execute(
    _i5.Observer<void>? observer, [
    _i7.SignInWithOAuthParam? params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            observer,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SignInPresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInPresenter extends _i1.Mock implements _i8.SignInPresenter {
  @override
  _i9.VoidCallback get authOnComplete => (super.noSuchMethod(
        Invocation.getter(#authOnComplete),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i9.VoidCallback);

  @override
  set authOnComplete(_i9.VoidCallback? _authOnComplete) => super.noSuchMethod(
        Invocation.setter(
          #authOnComplete,
          _authOnComplete,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.ValueSetter<dynamic> get authOnError => (super.noSuchMethod(
        Invocation.getter(#authOnError),
        returnValue: (dynamic value) {},
        returnValueForMissingStub: (dynamic value) {},
      ) as _i10.ValueSetter<dynamic>);

  @override
  set authOnError(_i10.ValueSetter<dynamic>? _authOnError) =>
      super.noSuchMethod(
        Invocation.setter(
          #authOnError,
          _authOnError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void signInWithAnonymous() => super.noSuchMethod(
        Invocation.method(
          #signInWithAnonymous,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void signInWithOAuth(_i11.OAuthProviderType? oauthProviderType) =>
      super.noSuchMethod(
        Invocation.method(
          #signInWithOAuth,
          [oauthProviderType],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
