// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/interface/pages/profile/profile_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i10;

import 'package:flutter/material.dart' as _i9;
import 'package:flutter_clean_architecture/flutter_clean_architecture.dart'
    as _i6;
import 'package:gynx_app/src/application/usecase/interactors/sign_out_interactor.dart'
    as _i7;
import 'package:gynx_app/src/application/usecase/interactors/suite_user_interactor.dart'
    as _i3;
import 'package:gynx_app/src/application/usecase/results/suite_user_result.dart'
    as _i5;
import 'package:gynx_app/src/interface/pages/profile/profile_presenter.dart'
    as _i8;
import 'package:logging/logging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogger_0 extends _i1.SmartFake implements _i2.Logger {
  _FakeLogger_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SuiteUserInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuiteUserInteractor extends _i1.Mock
    implements _i3.SuiteUserInteractor {
  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i4.Future<_i4.Stream<_i5.SuiteUserResult>> buildUseCaseStream(
          dynamic params) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUseCaseStream,
          [params],
        ),
        returnValue: _i4.Future<_i4.Stream<_i5.SuiteUserResult>>.value(
            _i4.Stream<_i5.SuiteUserResult>.empty()),
        returnValueForMissingStub:
            _i4.Future<_i4.Stream<_i5.SuiteUserResult>>.value(
                _i4.Stream<_i5.SuiteUserResult>.empty()),
      ) as _i4.Future<_i4.Stream<_i5.SuiteUserResult>>);

  @override
  void execute(
    _i6.Observer<_i5.SuiteUserResult>? observer, [
    dynamic params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            observer,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SignOutInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutInteractor extends _i1.Mock implements _i7.SignOutInteractor {
  @override
  _i2.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.Logger);

  @override
  _i4.Future<_i4.Stream<void>> buildUseCaseStream(dynamic params) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUseCaseStream,
          [params],
        ),
        returnValue:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
        returnValueForMissingStub:
            _i4.Future<_i4.Stream<void>>.value(_i4.Stream<void>.empty()),
      ) as _i4.Future<_i4.Stream<void>>);

  @override
  void execute(
    _i6.Observer<void>? observer, [
    dynamic params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            observer,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProfilePresenter].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfilePresenter extends _i1.Mock implements _i8.ProfilePresenter {
  @override
  _i9.ValueSetter<_i5.SuiteUserResult> get suiteUserOnNext =>
      (super.noSuchMethod(
        Invocation.getter(#suiteUserOnNext),
        returnValue: (_i5.SuiteUserResult value) {},
        returnValueForMissingStub: (_i5.SuiteUserResult value) {},
      ) as _i9.ValueSetter<_i5.SuiteUserResult>);

  @override
  set suiteUserOnNext(_i9.ValueSetter<_i5.SuiteUserResult>? _suiteUserOnNext) =>
      super.noSuchMethod(
        Invocation.setter(
          #suiteUserOnNext,
          _suiteUserOnNext,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.VoidCallback get suiteUserOnComplete => (super.noSuchMethod(
        Invocation.getter(#suiteUserOnComplete),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i10.VoidCallback);

  @override
  set suiteUserOnComplete(_i10.VoidCallback? _suiteUserOnComplete) =>
      super.noSuchMethod(
        Invocation.setter(
          #suiteUserOnComplete,
          _suiteUserOnComplete,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.ValueSetter<dynamic> get suiteUserOnError => (super.noSuchMethod(
        Invocation.getter(#suiteUserOnError),
        returnValue: (dynamic value) {},
        returnValueForMissingStub: (dynamic value) {},
      ) as _i9.ValueSetter<dynamic>);

  @override
  set suiteUserOnError(_i9.ValueSetter<dynamic>? _suiteUserOnError) =>
      super.noSuchMethod(
        Invocation.setter(
          #suiteUserOnError,
          _suiteUserOnError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.VoidCallback get signOutOnComplete => (super.noSuchMethod(
        Invocation.getter(#signOutOnComplete),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i10.VoidCallback);

  @override
  set signOutOnComplete(_i10.VoidCallback? _signOutOnComplete) =>
      super.noSuchMethod(
        Invocation.setter(
          #signOutOnComplete,
          _signOutOnComplete,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.ValueSetter<dynamic> get signOutOnError => (super.noSuchMethod(
        Invocation.getter(#signOutOnError),
        returnValue: (dynamic value) {},
        returnValueForMissingStub: (dynamic value) {},
      ) as _i9.ValueSetter<dynamic>);

  @override
  set signOutOnError(_i9.ValueSetter<dynamic>? _signOutOnError) =>
      super.noSuchMethod(
        Invocation.setter(
          #signOutOnError,
          _signOutOnError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void suiteUser() => super.noSuchMethod(
        Invocation.method(
          #suiteUser,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void signOut() => super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
