// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/interface/pages/profile/profile_presenter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_clean_architecture/flutter_clean_architecture.dart'
    as _i11;
import 'package:gynx_app/src/application/usecase/interactors/sign_out_interactor.dart'
    as _i12;
import 'package:gynx_app/src/application/usecase/interactors/suite_user_interactor.dart'
    as _i9;
import 'package:gynx_app/src/application/usecase/results/suite_user_result.dart'
    as _i10;
import 'package:gynx_app/src/domain/entities/t_user.dart' as _i2;
import 'package:gynx_app/src/domain/entities/t_user_profile.dart' as _i3;
import 'package:gynx_app/src/domain/repositories/auth_reposirory.dart' as _i5;
import 'package:gynx_app/src/domain/repositories/t_user_profile_reposirory.dart'
    as _i8;
import 'package:gynx_app/src/domain/repositories/t_user_reposirory.dart' as _i7;
import 'package:logging/logging.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTUser_0 extends _i1.SmartFake implements _i2.TUser {
  _FakeTUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTUserProfile_1 extends _i1.SmartFake implements _i3.TUserProfile {
  _FakeTUserProfile_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogger_2 extends _i1.SmartFake implements _i4.Logger {
  _FakeLogger_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  @override
  bool isSignedIn() => (super.noSuchMethod(
        Invocation.method(
          #isSignedIn,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> signInWithAnonymous() => (super.noSuchMethod(
        Invocation.method(
          #signInWithAnonymous,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithApple() => (super.noSuchMethod(
        Invocation.method(
          #signInWithApple,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> linkWithApple() => (super.noSuchMethod(
        Invocation.method(
          #linkWithApple,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> linkWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #linkWithGoogle,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> linkWithX() => (super.noSuchMethod(
        Invocation.method(
          #linkWithX,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> linkWithTwitch() => (super.noSuchMethod(
        Invocation.method(
          #linkWithTwitch,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> linkWithDiscord() => (super.noSuchMethod(
        Invocation.method(
          #linkWithDiscord,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [TUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTUserRepository extends _i1.Mock implements _i7.TUserRepository {
  @override
  _i6.Future<void> update(_i2.TUser? tUser) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [tUser],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.TUser> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i6.Future<_i2.TUser>.value(_FakeTUser_0(
          this,
          Invocation.method(
            #findById,
            [id],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.TUser>.value(_FakeTUser_0(
          this,
          Invocation.method(
            #findById,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.TUser>);

  @override
  _i6.Future<_i2.TUser> findByGynxId(String? gynxId) => (super.noSuchMethod(
        Invocation.method(
          #findByGynxId,
          [gynxId],
        ),
        returnValue: _i6.Future<_i2.TUser>.value(_FakeTUser_0(
          this,
          Invocation.method(
            #findByGynxId,
            [gynxId],
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.TUser>.value(_FakeTUser_0(
          this,
          Invocation.method(
            #findByGynxId,
            [gynxId],
          ),
        )),
      ) as _i6.Future<_i2.TUser>);
}

/// A class which mocks [TUserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTUserProfileRepository extends _i1.Mock
    implements _i8.TUserProfileRepository {
  @override
  _i6.Future<void> update(_i3.TUserProfile? tUserProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [tUserProfile],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.TUserProfile> findByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #findByUserId,
          [userId],
        ),
        returnValue: _i6.Future<_i3.TUserProfile>.value(_FakeTUserProfile_1(
          this,
          Invocation.method(
            #findByUserId,
            [userId],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.TUserProfile>.value(_FakeTUserProfile_1(
          this,
          Invocation.method(
            #findByUserId,
            [userId],
          ),
        )),
      ) as _i6.Future<_i3.TUserProfile>);
}

/// A class which mocks [SuiteUserInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuiteUserInteractor extends _i1.Mock
    implements _i9.SuiteUserInteractor {
  @override
  _i4.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_2(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_2(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i4.Logger);

  @override
  _i6.Future<_i6.Stream<_i10.SuiteUserResult>> buildUseCaseStream(
          dynamic params) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUseCaseStream,
          [params],
        ),
        returnValue: _i6.Future<_i6.Stream<_i10.SuiteUserResult>>.value(
            _i6.Stream<_i10.SuiteUserResult>.empty()),
        returnValueForMissingStub:
            _i6.Future<_i6.Stream<_i10.SuiteUserResult>>.value(
                _i6.Stream<_i10.SuiteUserResult>.empty()),
      ) as _i6.Future<_i6.Stream<_i10.SuiteUserResult>>);

  @override
  void execute(
    _i11.Observer<_i10.SuiteUserResult>? observer, [
    dynamic params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            observer,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SignOutInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutInteractor extends _i1.Mock implements _i12.SignOutInteractor {
  @override
  _i4.Logger get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeLogger_2(
          this,
          Invocation.getter(#logger),
        ),
        returnValueForMissingStub: _FakeLogger_2(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i4.Logger);

  @override
  _i6.Future<_i6.Stream<void>> buildUseCaseStream(dynamic params) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildUseCaseStream,
          [params],
        ),
        returnValue:
            _i6.Future<_i6.Stream<void>>.value(_i6.Stream<void>.empty()),
        returnValueForMissingStub:
            _i6.Future<_i6.Stream<void>>.value(_i6.Stream<void>.empty()),
      ) as _i6.Future<_i6.Stream<void>>);

  @override
  void execute(
    _i11.Observer<void>? observer, [
    dynamic params,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            observer,
            params,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
