// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/presentation/pages/home/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:gynx_app/src/domain/entities/v_post.dart' as _i2;
import 'package:gynx_app/src/domain/enums/timeline_type.dart' as _i9;
import 'package:gynx_app/src/domain/models/media_list.dart' as _i7;
import 'package:gynx_app/src/domain/models/v_post_list.dart' as _i4;
import 'package:gynx_app/src/domain/usecases/create_post_usecase.dart' as _i5;
import 'package:gynx_app/src/presentation/notifiers/timeline_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVPost_0 extends _i1.SmartFake implements _i2.VPost {
  _FakeVPost_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoDisposeAsyncNotifierProviderRef_1<T> extends _i1.SmartFake
    implements _i3.AutoDisposeAsyncNotifierProviderRef<T> {
  _FakeAutoDisposeAsyncNotifierProviderRef_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncValue_2<T> extends _i1.SmartFake implements _i3.AsyncValue<T> {
  _FakeAsyncValue_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVPostList_3 extends _i1.SmartFake implements _i4.VPostList {
  _FakeVPostList_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CreatePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreatePostUseCase extends _i1.Mock implements _i5.CreatePostUseCase {
  @override
  _i6.Future<_i2.VPost> execute({
    required String? text,
    required _i7.MediaList? mediaList,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #text: text,
            #mediaList: mediaList,
          },
        ),
        returnValue: _i6.Future<_i2.VPost>.value(_FakeVPost_0(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #text: text,
              #mediaList: mediaList,
            },
          ),
        )),
        returnValueForMissingStub: _i6.Future<_i2.VPost>.value(_FakeVPost_0(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #text: text,
              #mediaList: mediaList,
            },
          ),
        )),
      ) as _i6.Future<_i2.VPost>);
}

/// A class which mocks [TimelineNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimelineNotifier extends _i1.Mock implements _i8.TimelineNotifier {
  @override
  _i9.TimelineType get timelineType => (super.noSuchMethod(
        Invocation.getter(#timelineType),
        returnValue: _i9.TimelineType.follow,
        returnValueForMissingStub: _i9.TimelineType.follow,
      ) as _i9.TimelineType);

  @override
  set timelineType(_i9.TimelineType? _timelineType) => super.noSuchMethod(
        Invocation.setter(
          #timelineType,
          _timelineType,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AutoDisposeAsyncNotifierProviderRef<_i4.VPostList> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeAsyncNotifierProviderRef_1<_i4.VPostList>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeAutoDisposeAsyncNotifierProviderRef_1<_i4.VPostList>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i3.AutoDisposeAsyncNotifierProviderRef<_i4.VPostList>);

  @override
  _i3.AsyncValue<_i4.VPostList> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_2<_i4.VPostList>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeAsyncValue_2<_i4.VPostList>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AsyncValue<_i4.VPostList>);

  @override
  set state(_i3.AsyncValue<_i4.VPostList>? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i4.VPostList> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i6.Future<_i4.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.getter(#future),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.getter(#future),
        )),
      ) as _i6.Future<_i4.VPostList>);

  @override
  _i6.FutureOr<_i4.VPostList> build(_i9.TimelineType? timelineType) =>
      (super.noSuchMethod(
        Invocation.method(
          #build,
          [timelineType],
        ),
        returnValue: _i6.Future<_i4.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #build,
            [timelineType],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #build,
            [timelineType],
          ),
        )),
      ) as _i6.FutureOr<_i4.VPostList>);

  @override
  void add(_i2.VPost? vPost) => super.noSuchMethod(
        Invocation.method(
          #add,
          [vPost],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addAll(_i4.VPostList? vPostList) => super.noSuchMethod(
        Invocation.method(
          #addAll,
          [vPostList],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i3.AsyncValue<_i4.VPostList>?,
      _i3.AsyncValue<_i4.VPostList>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i4.VPostList> update(
    _i6.FutureOr<_i4.VPostList> Function(_i4.VPostList)? cb, {
    _i6.FutureOr<_i4.VPostList> Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [cb],
          {#onError: onError},
        ),
        returnValue: _i6.Future<_i4.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.VPostList>.value(_FakeVPostList_3(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
      ) as _i6.Future<_i4.VPostList>);

  @override
  bool updateShouldNotify(
    _i3.AsyncValue<_i4.VPostList>? previous,
    _i3.AsyncValue<_i4.VPostList>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
