// Mocks generated by Mockito 5.4.4 from annotations
// in gynx_app/test/src/presentation/pages/home/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:gynx_app/src/domain/entities/v_post.dart' as _i2;
import 'package:gynx_app/src/domain/models/media_list.dart' as _i9;
import 'package:gynx_app/src/domain/models/suite_user.dart' as _i4;
import 'package:gynx_app/src/domain/models/v_post_list.dart' as _i6;
import 'package:gynx_app/src/domain/usecases/create_post_usecase.dart' as _i7;
import 'package:gynx_app/src/presentation/notifiers/suite_user_notifier.dart'
    as _i10;
import 'package:gynx_app/src/presentation/notifiers/timeline_notifier.dart'
    as _i11;
import 'package:gynx_app/src/presentation/notifiers/timeline_notifier_mixin.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVPost_0 extends _i1.SmartFake implements _i2.VPost {
  _FakeVPost_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutoDisposeAsyncNotifierProviderRef_1<T> extends _i1.SmartFake
    implements _i3.AutoDisposeAsyncNotifierProviderRef<T> {
  _FakeAutoDisposeAsyncNotifierProviderRef_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAsyncValue_2<T> extends _i1.SmartFake implements _i3.AsyncValue<T> {
  _FakeAsyncValue_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSuiteUser_3 extends _i1.SmartFake implements _i4.SuiteUser {
  _FakeSuiteUser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimelineState_4 extends _i1.SmartFake implements _i5.TimelineState {
  _FakeTimelineState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVPostList_5 extends _i1.SmartFake implements _i6.VPostList {
  _FakeVPostList_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CreatePostUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreatePostUseCase extends _i1.Mock implements _i7.CreatePostUseCase {
  @override
  _i8.Future<_i2.VPost> execute({
    required String? text,
    required _i9.MediaList? mediaList,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #text: text,
            #mediaList: mediaList,
          },
        ),
        returnValue: _i8.Future<_i2.VPost>.value(_FakeVPost_0(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #text: text,
              #mediaList: mediaList,
            },
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i2.VPost>.value(_FakeVPost_0(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #text: text,
              #mediaList: mediaList,
            },
          ),
        )),
      ) as _i8.Future<_i2.VPost>);
}

/// A class which mocks [SuiteUserNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuiteUserNotifier extends _i1.Mock implements _i10.SuiteUserNotifier {
  @override
  _i3.AutoDisposeAsyncNotifierProviderRef<_i4.SuiteUser> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue: _FakeAutoDisposeAsyncNotifierProviderRef_1<_i4.SuiteUser>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeAutoDisposeAsyncNotifierProviderRef_1<_i4.SuiteUser>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i3.AutoDisposeAsyncNotifierProviderRef<_i4.SuiteUser>);

  @override
  _i3.AsyncValue<_i4.SuiteUser> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_2<_i4.SuiteUser>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeAsyncValue_2<_i4.SuiteUser>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AsyncValue<_i4.SuiteUser>);

  @override
  set state(_i3.AsyncValue<_i4.SuiteUser>? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i4.SuiteUser> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i8.Future<_i4.SuiteUser>.value(_FakeSuiteUser_3(
          this,
          Invocation.getter(#future),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.SuiteUser>.value(_FakeSuiteUser_3(
          this,
          Invocation.getter(#future),
        )),
      ) as _i8.Future<_i4.SuiteUser>);

  @override
  _i8.FutureOr<_i4.SuiteUser> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _i8.Future<_i4.SuiteUser>.value(_FakeSuiteUser_3(
          this,
          Invocation.method(
            #build,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.SuiteUser>.value(_FakeSuiteUser_3(
          this,
          Invocation.method(
            #build,
            [],
          ),
        )),
      ) as _i8.FutureOr<_i4.SuiteUser>);

  @override
  void addPost(_i2.VPost? vPost) => super.noSuchMethod(
        Invocation.method(
          #addPost,
          [vPost],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void listenSelf(
    void Function(
      _i3.AsyncValue<_i4.SuiteUser>?,
      _i3.AsyncValue<_i4.SuiteUser>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i4.SuiteUser> update(
    _i8.FutureOr<_i4.SuiteUser> Function(_i4.SuiteUser)? cb, {
    _i8.FutureOr<_i4.SuiteUser> Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [cb],
          {#onError: onError},
        ),
        returnValue: _i8.Future<_i4.SuiteUser>.value(_FakeSuiteUser_3(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i4.SuiteUser>.value(_FakeSuiteUser_3(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
      ) as _i8.Future<_i4.SuiteUser>);

  @override
  bool updateShouldNotify(
    _i3.AsyncValue<_i4.SuiteUser>? previous,
    _i3.AsyncValue<_i4.SuiteUser>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [TimelineNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimelineNotifier extends _i1.Mock implements _i11.TimelineNotifier {
  @override
  _i3.AutoDisposeAsyncNotifierProviderRef<_i5.TimelineState>
      get timelineNotifierRef => (super.noSuchMethod(
            Invocation.getter(#timelineNotifierRef),
            returnValue:
                _FakeAutoDisposeAsyncNotifierProviderRef_1<_i5.TimelineState>(
              this,
              Invocation.getter(#timelineNotifierRef),
            ),
            returnValueForMissingStub:
                _FakeAutoDisposeAsyncNotifierProviderRef_1<_i5.TimelineState>(
              this,
              Invocation.getter(#timelineNotifierRef),
            ),
          ) as _i3.AutoDisposeAsyncNotifierProviderRef<_i5.TimelineState>);

  @override
  _i3.AsyncValue<_i5.TimelineState> get timelineState => (super.noSuchMethod(
        Invocation.getter(#timelineState),
        returnValue: _FakeAsyncValue_2<_i5.TimelineState>(
          this,
          Invocation.getter(#timelineState),
        ),
        returnValueForMissingStub: _FakeAsyncValue_2<_i5.TimelineState>(
          this,
          Invocation.getter(#timelineState),
        ),
      ) as _i3.AsyncValue<_i5.TimelineState>);

  @override
  set timelineState(_i3.AsyncValue<_i5.TimelineState>? value) =>
      super.noSuchMethod(
        Invocation.setter(
          #timelineState,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.AutoDisposeAsyncNotifierProviderRef<_i5.TimelineState> get ref =>
      (super.noSuchMethod(
        Invocation.getter(#ref),
        returnValue:
            _FakeAutoDisposeAsyncNotifierProviderRef_1<_i5.TimelineState>(
          this,
          Invocation.getter(#ref),
        ),
        returnValueForMissingStub:
            _FakeAutoDisposeAsyncNotifierProviderRef_1<_i5.TimelineState>(
          this,
          Invocation.getter(#ref),
        ),
      ) as _i3.AutoDisposeAsyncNotifierProviderRef<_i5.TimelineState>);

  @override
  _i3.AsyncValue<_i5.TimelineState> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_2<_i5.TimelineState>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeAsyncValue_2<_i5.TimelineState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AsyncValue<_i5.TimelineState>);

  @override
  set state(_i3.AsyncValue<_i5.TimelineState>? newState) => super.noSuchMethod(
        Invocation.setter(
          #state,
          newState,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i5.TimelineState> get future => (super.noSuchMethod(
        Invocation.getter(#future),
        returnValue: _i8.Future<_i5.TimelineState>.value(_FakeTimelineState_4(
          this,
          Invocation.getter(#future),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.TimelineState>.value(_FakeTimelineState_4(
          this,
          Invocation.getter(#future),
        )),
      ) as _i8.Future<_i5.TimelineState>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i8.FutureOr<_i5.TimelineState> build() => (super.noSuchMethod(
        Invocation.method(
          #build,
          [],
        ),
        returnValue: _i8.Future<_i5.TimelineState>.value(_FakeTimelineState_4(
          this,
          Invocation.method(
            #build,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.TimelineState>.value(_FakeTimelineState_4(
          this,
          Invocation.method(
            #build,
            [],
          ),
        )),
      ) as _i8.FutureOr<_i5.TimelineState>);

  @override
  _i8.Future<_i6.VPostList> fetchBySincePostId(int? sincePostId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBySincePostId,
          [sincePostId],
        ),
        returnValue: _i8.Future<_i6.VPostList>.value(_FakeVPostList_5(
          this,
          Invocation.method(
            #fetchBySincePostId,
            [sincePostId],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i6.VPostList>.value(_FakeVPostList_5(
          this,
          Invocation.method(
            #fetchBySincePostId,
            [sincePostId],
          ),
        )),
      ) as _i8.Future<_i6.VPostList>);

  @override
  _i8.Future<_i6.VPostList> fetchByMaxPostId(int? maxPostId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchByMaxPostId,
          [maxPostId],
        ),
        returnValue: _i8.Future<_i6.VPostList>.value(_FakeVPostList_5(
          this,
          Invocation.method(
            #fetchByMaxPostId,
            [maxPostId],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i6.VPostList>.value(_FakeVPostList_5(
          this,
          Invocation.method(
            #fetchByMaxPostId,
            [maxPostId],
          ),
        )),
      ) as _i8.Future<_i6.VPostList>);

  @override
  void listenSelf(
    void Function(
      _i3.AsyncValue<_i5.TimelineState>?,
      _i3.AsyncValue<_i5.TimelineState>,
    )? listener, {
    void Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #listenSelf,
          [listener],
          {#onError: onError},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i5.TimelineState> update(
    _i8.FutureOr<_i5.TimelineState> Function(_i5.TimelineState)? cb, {
    _i8.FutureOr<_i5.TimelineState> Function(
      Object,
      StackTrace,
    )? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [cb],
          {#onError: onError},
        ),
        returnValue: _i8.Future<_i5.TimelineState>.value(_FakeTimelineState_4(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i5.TimelineState>.value(_FakeTimelineState_4(
          this,
          Invocation.method(
            #update,
            [cb],
            {#onError: onError},
          ),
        )),
      ) as _i8.Future<_i5.TimelineState>);

  @override
  bool updateShouldNotify(
    _i3.AsyncValue<_i5.TimelineState>? previous,
    _i3.AsyncValue<_i5.TimelineState>? next,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            previous,
            next,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int getByIndex(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getByIndex,
          [index],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i8.Future<void> fetchNext() => (super.noSuchMethod(
        Invocation.method(
          #fetchNext,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> fetchPrevious() => (super.noSuchMethod(
        Invocation.method(
          #fetchPrevious,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void add(int? postId) => super.noSuchMethod(
        Invocation.method(
          #add,
          [postId],
        ),
        returnValueForMissingStub: null,
      );
}
